# TODO: Manual versioning?
execute_process(COMMAND "git" "describe" "--tags" "--always" WORKING_DIRECTORY "${playd_SOURCE_DIR}" RESULT_VARIABLE NOT_GIT_REPO OUTPUT_VARIABLE PROGVER OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT_GIT_REPO)
  message(FATAL "Not a git repo")
else()
  add_definitions(-DPD_VERSION="${PROGVER}")
endif()

# Set project version string
if (DEFINED PROGVER)
  string (REGEX REPLACE "^v([0-9]+)\.([0-9]+)\.([0-9]+)-([0-9]+)-(.*)" "\\1;\\2;\\3;\\4" _versionComponents "${PROGVER}")
  list (LENGTH _versionComponents _len)
  if (${_len} GREATER 0)
    list(GET _versionComponents 0 V_MAJOR)
    set(PROJECTVER "${V_MAJOR}")
  endif()
  if (${_len} GREATER 1)
    list(GET _versionComponents 1 V_MINOR)
    string(APPEND PROJECTVER ".${V_MINOR}")
  endif()
  if (${_len} GREATER 2)
    list(GET _versionComponents 2 V_PATCH)
    string(APPEND PROJECTVER ".${V_PATCH}")
  endif()
  if (${_len} GREATER 3)
    list(GET _versionComponents 3 V_TWEAK)
    string(APPEND PROJECTVER ".${V_TWEAK}")
  endif()
endif()
