var annotated =
[
    [ "Audio", "classAudio.html", "classAudio" ],
    [ "AudioSink", "classAudioSink.html", "classAudioSink" ],
    [ "AudioSinkConfigurator", "classAudioSinkConfigurator.html", "classAudioSinkConfigurator" ],
    [ "AudioSource", "classAudioSource.html", "classAudioSource" ],
    [ "AudioSystem", "classAudioSystem.html", "classAudioSystem" ],
    [ "CommandHandler", "classCommandHandler.html", "classCommandHandler" ],
    [ "CommandResult", "classCommandResult.html", "classCommandResult" ],
    [ "ConfigError", "classConfigError.html", "classConfigError" ],
    [ "Connection", "classConnection.html", "classConnection" ],
    [ "ConnectionPool", "classConnectionPool.html", "classConnectionPool" ],
    [ "Debug", "classDebug.html", "classDebug" ],
    [ "Error", "classError.html", "classError" ],
    [ "FileError", "classFileError.html", "classFileError" ],
    [ "InternalError", "classInternalError.html", "classInternalError" ],
    [ "IoCore", "classIoCore.html", "classIoCore" ],
    [ "NetError", "classNetError.html", "classNetError" ],
    [ "PaSoxAudioSystem", "classPaSoxAudioSystem.html", "classPaSoxAudioSystem" ],
    [ "PipeAudio", "classPipeAudio.html", "classPipeAudio" ],
    [ "Playd", "classPlayd.html", "classPlayd" ],
    [ "Player", "classPlayer.html", "classPlayer" ],
    [ "PlayerFile", "classPlayerFile.html", "classPlayerFile" ],
    [ "PlayerPosition", "classPlayerPosition.html", "classPlayerPosition" ],
    [ "PlayerState", "classPlayerState.html", "classPlayerState" ],
    [ "ResponseSink", "classResponseSink.html", "classResponseSink" ],
    [ "ResponseSource", "classResponseSource.html", "classResponseSource" ],
    [ "RingBuffer", "classRingBuffer.html", "classRingBuffer" ],
    [ "SeekError", "classSeekError.html", "classSeekError" ],
    [ "Tokeniser", "classTokeniser.html", "classTokeniser" ],
    [ "WriteReq", "structWriteReq.html", "structWriteReq" ]
];