URY playd: PlayerState Class Reference
PlayerState Class Reference
An object holding and representing the current state of a Player.
#include <player_state.hpp>
Public Types
enum State : std::uint8_t {
State::STARTING, State::EJECTED, State::STOPPED, State::PLAYING,
State::QUITTING
}
Enumeration of states that the player can be in.
typedef std::initializer_list
< State > List
A list of states, used for In.
Public Member Functions
PlayerState (const ResponseSink *state_sink)
Constructs a PlayerState.
void Emit (const ResponseSink &sink) const override
Announces the current state to a ResponseSink.
bool In (List states) const
Checks whether the current state is in a given list of states.
bool IsRunning () const
Returns whether the player is still running.
void Set (State state)
Sets the player's current state.
Public Member Functions inherited from ResponseSource
ResponseSource (const ResponseSink *push_sink)
Constructs a ResponseSource.
Static Public Attributes
static const List AUDIO_PLAYING_STATES
List of states in which the player is playing something.
static const List AUDIO_LOADED_STATES
List of states in which some audio is loaded.
Private Attributes
State current
The current state.
Static Private Attributes
static const std::string STRINGS []
A mapping between states and their human-readable names.
Additional Inherited Members
Protected Member Functions inherited from ResponseSource
void Push () const
Calls an Emit on the registered ResponseSink.
Detailed Description
An object holding and representing the current state of a Player.
See also
Player
PlayerPosition
Definition at line 23 of file player_state.hpp.
Member Enumeration Documentation
enum PlayerState::State : std::uint8_t strong
Enumeration of states that the player can be in.
The player is effectively a finite-state machine whose behaviour at any given time is dictated by the current state, which is represented by an instance of State.
Note
If you're adding new states here, update PlayerState::STRINGS.
See also
PlayerState::STRINGS
Enumerator
STARTING
The player has just initialised.
EJECTED
The player has no song loaded.
STOPPED
The player has a song loaded and not playing.
PLAYING
The player has a song loaded and playing.
QUITTING
The player is about to terminate.
Definition at line 34 of file player_state.hpp.
                      : std::uint8_t {
         STARTING,
         EJECTED,
         STOPPED,
         PLAYING,
         QUITTING
     };
Constructor & Destructor Documentation
PlayerState::PlayerState (const ResponseSink * state_sink)
Constructs a PlayerState.
Parameters
state_sink The sink to which STATE notifications are sent.
Definition at line 29 of file player_state.cpp.
     : ResponseSource(state_sink), current(State::EJECTED)
 {
 }
Member Function Documentation
void PlayerState::Emit (const ResponseSink & sink) const override virtual
Announces the current state to a ResponseSink.
Parameters
sink The ResponseSink to which the current state shall be emitted.
Implements ResponseSource.
Definition at line 34 of file player_state.cpp.
References current, ResponseSink::Respond(), STATE, and STRINGS.
Referenced by Player::WelcomeClient().
 {
     auto c = static_cast<int>(this->current);
     responder.Respond(ResponseCode::STATE, PlayerState::STRINGS[c]);
 }
bool PlayerState::In (PlayerState::List states) const
Checks whether the current state is in a given list of states.
Parameters
states The initialiser list of states.
Returns
True if the state is in the List; false otherwise.
Definition at line 40 of file player_state.cpp.
References current.
Referenced by Player::Eject(), Player::Play(), Player::Seek(), and Player::Stop().
 {
     return std::find(states.begin(), states.end(), this->current) !=
            states.end();
 }
bool PlayerState::IsRunning () const
Returns whether the player is still running.
Returns
True if the player is not in the QUITTING state; false otherwise.
Definition at line 46 of file player_state.cpp.
References current, and QUITTING.
Referenced by Player::Update().
 {
     return this->current != State::QUITTING;
 }
void PlayerState::Set (PlayerState::State state)
Sets the player's current state.
This will automatically emit the new state to any responder that has been registered with this PlayerState using SetResponseSink.
Parameters
state The new state.
Definition at line 61 of file player_state.cpp.
References current, and ResponseSource::Push().
Referenced by Player::Eject(), Player::Load(), Player::Play(), Player::Quit(), and Player::Stop().
 {
     this->current = state;
     this->Push();
 }
Member Data Documentation
const PlayerState::List PlayerState::AUDIO_LOADED_STATES static
Initial value:
= {
    PlayerState::State::PLAYING, PlayerState::State::STOPPED
}
List of states in which some audio is loaded.
Definition at line 49 of file player_state.hpp.
Referenced by Player::Eject(), and Player::Seek().
const PlayerState::List PlayerState::AUDIO_PLAYING_STATES static
Initial value:
= {
    PlayerState::State::PLAYING
}
List of states in which the player is playing something.
Definition at line 46 of file player_state.hpp.
Referenced by Player::Stop().
const std::string PlayerState::STRINGS static private
Initial value:
= {
    "Starting",
    "Ejected",
    "Stopped",
    "Playing",
    "Quitting",
}
A mapping between states and their human-readable names.
Implemented as an array indexed by the int equivalent of the state enum.
See also
PlayerState::State
Definition at line 93 of file player_state.hpp.
Referenced by Emit().
The documentation for this class was generated from the following files:
src/player/player_state.hpp
src/player/player_state.cpp