URY playd: PaSoxAudioSystem Class Reference
PaSoxAudioSystem Class Reference
Implementation of AudioSystem using libsox and PortAudio.
#include <audio_system.hpp>
Public Member Functions
PaSoxAudioSystem ()
Constructs a PaSoxAudioSystem, initialising its libraries.
virtual ~PaSoxAudioSystem ()
Destructs an PaSoxAudioSystem, uninitialising its libraries.
Audio * Load (const std::string &path) const override
Loads a file, creating an Audio for it.
void SetDeviceID (int id) override
Sets the current device ID.
std::vector< AudioSystem::Device > GetDevicesInfo () override
Gets the number and name of each output device entry in the AudioSystem.
bool IsOutputDevice (int id) override
Can a sound device output sound?
portaudio::Stream * Configure (const AudioSource &source, portaudio::CallbackInterface &cb) const override
Configures and returns a PortAudio stream.
Static Private Member Functions
static const portaudio::Device & PaDevice (const std::string &id_string)
Converts a string device ID to a PortAudio device.
static portaudio::SampleDataFormat PaFormat (SampleFormat fmt)
Converts a sample format identifier from playd to PortAudio.
Private Attributes
std::string device_id
The current device ID.
Additional Inherited Members
Public Types inherited from AudioSystem
typedef std::pair< int,
std::string > Device
Type for device entries.
Detailed Description
Implementation of AudioSystem using libsox and PortAudio.
PaSoxAudioSystem is a RAII-style class: it loads the audio libraries on construction and unloads them on termination. As such, it's probably not wise to construct multiple AudioSystem instances.
Definition at line 82 of file audio_system.hpp.
Constructor & Destructor Documentation
PaSoxAudioSystem::PaSoxAudioSystem ()
Constructs a PaSoxAudioSystem, initialising its libraries.
This sets the current device ID to a sane default; use SetDeviceID to change it.
Definition at line 42 of file audio_system.cpp.
References device_id.
 {
     portaudio::System::initialize();
     sox_format_init();
     this->device_id = -1;
 }
Member Function Documentation
portaudio::Stream * PaSoxAudioSystem::Configure (const AudioSource & source, portaudio::CallbackInterface & cb) const override virtual
Configures and returns a PortAudio stream.
Parameters
source The audio source to use to configure the stream.
cb The object that PortAudio will call to receive audio.
Returns
The configured PortAudio stream.
Implements AudioSinkConfigurator.
Definition at line 90 of file audio_system.cpp.
References AudioSource::BufferSampleCapacity(), AudioSource::ChannelCount(), device_id, AudioSource::OutputSampleFormat(), PaDevice(), PaFormat(), and AudioSource::SampleRate().
 {
     std::uint8_t channel_count = source.ChannelCount();
     SampleFormat sample_format = source.OutputSampleFormat();
     double sample_rate = source.SampleRate();
     size_t buffer_size = source.BufferSampleCapacity();
     const portaudio::Device &device = PaDevice(this->device_id);
     portaudio::DirectionSpecificStreamParameters out_pars(
                     device, channel_count, PaFormat(sample_format), true,
                     device.defaultLowOutputLatency(), nullptr);
     portaudio::StreamParameters pars(
                     portaudio::DirectionSpecificStreamParameters::null(),
                     out_pars, sample_rate, buffer_size, paClipOff);
     return new portaudio::InterfaceCallbackStream(pars, cb);
 }
std::vector< AudioSystem::Device > PaSoxAudioSystem::GetDevicesInfo () override virtual
Gets the number and name of each output device entry in the AudioSystem.
Returns
List of output devices, as strings.
Implements AudioSystem.
Definition at line 56 of file audio_system.cpp.
Referenced by Playd::Run().
 {
     auto &pa = portaudio::System::instance();
     std::vector<AudioSystem::Device> list;
     for (auto d = pa.devicesBegin(); d != pa.devicesEnd(); ++d) {
         if (!(*d).isInputOnlyDevice()) {
             list.push_back(std::make_pair((*d).index(), (*d).name()));
         }
     }
     return list;
 }
bool PaSoxAudioSystem::IsOutputDevice (int id) override virtual
Can a sound device output sound?
Parameters
id Device ID.
Returns
If the device can handle outputting sound.
Implements AudioSystem.
Definition at line 69 of file audio_system.cpp.
Referenced by Playd::GetDeviceID().
 {
     auto &pa = portaudio::System::instance();
     if (id < 0 || id >= pa.deviceCount()) return false;
     portaudio::Device &dev = pa.deviceByIndex(id);
     return !dev.isInputOnlyDevice();
 }
Audio * PaSoxAudioSystem::Load (const std::string & path) const override virtual
Loads a file, creating an Audio for it.
Parameters
path The path to a file.
Returns
The Audio for that file.
Implements AudioSystem.
Definition at line 83 of file audio_system.cpp.
 {
     auto source = new AudioSource(path);
     auto sink = new AudioSink(*source, *this);
     return new PipeAudio(source, sink);
 }
const portaudio::Device & PaSoxAudioSystem::PaDevice (const std::string & id_string) static private
Converts a string device ID to a PortAudio device.
Parameters
id_string The device ID, as a string.
Returns
The device.
Definition at line 110 of file audio_system.cpp.
References MSG_DEV_BADID.
Referenced by Configure().
 {
     auto &pa = portaudio::System::instance();
     PaDeviceIndex id_pa = std::stoi(id);
     if (pa.deviceCount() <= id_pa) throw ConfigError(MSG_DEV_BADID);
     return pa.deviceByIndex(id_pa);
 }
portaudio::SampleDataFormat PaSoxAudioSystem::PaFormat (SampleFormat fmt) static private
Converts a sample format identifier from playd to PortAudio.
Parameters
fmt The playd sample format identifier.
Returns
The PortAudio equivalent of the given SampleFormat.
Definition at line 128 of file audio_system.cpp.
References MSG_DECODE_BADRATE.
Referenced by Configure().
 {
     try {
         return pa_from_sf.at(fmt);
     } catch (std::out_of_range) {
         throw FileError(MSG_DECODE_BADRATE);
     }
 }
void PaSoxAudioSystem::SetDeviceID (int id) override virtual
Sets the current device ID.
Parameters
id The device ID to use for subsequent Audios.
Implements AudioSystem.
Definition at line 78 of file audio_system.cpp.
References device_id.
Referenced by Playd::Run().
 {
     this->device_id = std::to_string(id);
 }
The documentation for this class was generated from the following files:
src/audio/audio_system.hpp
src/audio/audio_system.cpp