URY playd: AudioSystem Class Reference
AudioSystem Class Reference
An AudioSystem represents the entire audio stack used by playd.
#include <audio_system.hpp>
Public Types
using Device = std::pair< int, std::string >
Type for device entries.
Public Member Functions
AudioSystem ()
Constructs an AudioSystem, initialising its libraries.
~AudioSystem ()
Destructs an AudioSystem, uninitialising its libraries.
Audio * Load (const std::string &path) const
Loads a file, creating an Audio for it.
void SetDeviceID (int id)
Sets the current device ID.
std::vector< AudioSystem::Device > GetDevicesInfo ()
Gets the number and name of each output device entry in the AudioSystem.
bool IsOutputDevice (int id)
Can a sound device output sound?
portaudio::Stream * Configure (std::uint8_t channel_count, SampleFormat sample_format, double sample_rate, size_t buffer_size, portaudio::CallbackInterface &cb) const
Configures and returns a PortAudio stream.
Private Member Functions
const portaudio::Device & PaDeviceFrom (const std::string &id_string) const
Converts a string device ID to a PortAudio device.
portaudio::SampleDataFormat PaSampleFormatFrom (SampleFormat fmt) const
Converts a sample format identifier from playd to PortAudio.
Private Attributes
std::string device_id
The current device ID.
Detailed Description
An AudioSystem represents the entire audio stack used by playd.
The AudioSystem is responsible for creating Audio instances, enumerating and resolving device IDs, and initialising and terminating the audio libraries.
AudioSystem is a RAII-style class: it loads the audio libraries on construction and unloads them on termination. As such, it's probably not wise to construct multiple AudioSystem instances.
Definition at line 40 of file audio_system.hpp.
Constructor & Destructor Documentation
AudioSystem::AudioSystem ()
Constructs an AudioSystem, initialising its libraries.
This sets the current device ID to a sane default; use SetDeviceID to change it.
Definition at line 41 of file audio_system.cpp.
References device_id.
 {
     portaudio::System::initialize();
     sox_format_init();
     this->device_id = -1;
 }
Member Function Documentation
portaudio::Stream * AudioSystem::Configure (std::uint8_t channel_count, SampleFormat sample_format, double sample_rate, size_t buffer_size, portaudio::CallbackInterface & cb) const
Configures and returns a PortAudio stream.
Parameters
channel_count The number of channels of the stream will receive.
sample_format The format of the samples the stream will receive.
sample_rate The rate of the samples the stream will receive.
buffer_size The size of the buffer the stream should allocate.
cb The object that PortAudio will call to receive audio.
Returns
The configured PortAudio stream.
Definition at line 96 of file audio_system.cpp.
References device_id, PaDeviceFrom(), and PaSampleFormatFrom().
Referenced by Load().
 {
     const portaudio::Device &device = PaDeviceFrom(this->device_id);
     portaudio::DirectionSpecificStreamParameters out_pars(
                     device, channel_count,
                     PaSampleFormatFrom(sample_format), true,
                     device.defaultLowOutputLatency(), nullptr);
     portaudio::StreamParameters pars(
                     portaudio::DirectionSpecificStreamParameters::null(),
                     out_pars, sample_rate, buffer_size, paClipOff);
     return new portaudio::InterfaceCallbackStream(pars, cb);
 }
std::vector< AudioSystem::Device > AudioSystem::GetDevicesInfo ()
Gets the number and name of each output device entry in the AudioSystem.
Returns
List of output devices, as strings.
Definition at line 55 of file audio_system.cpp.
Referenced by playd::GetDeviceID(), and playd::Run().
 {
     auto &pa = portaudio::System::instance();
     std::vector<AudioSystem::Device> list;
     for (auto d = pa.devicesBegin(); d != pa.devicesEnd(); ++d) {
         if (!(*d).isInputOnlyDevice()) {
             list.push_back(std::make_pair((*d).index(),
                                           (*d).name()));
         }
     }
     return list;
 }
bool AudioSystem::IsOutputDevice (int id)
Can a sound device output sound?
Parameters
id Device ID.
Returns
If the device can handle outputting sound.
Definition at line 69 of file audio_system.cpp.
Referenced by playd::GetDeviceID().
 {
     auto &pa = portaudio::System::instance();
     if (id < 0 || id >= pa.deviceCount()) return false;
     portaudio::Device &dev = pa.deviceByIndex(id);
     return !dev.isInputOnlyDevice();
 }
Audio * AudioSystem::Load (const std::string & path) const
Loads a file, creating an Audio for it.
Parameters
path The path to a file.
Returns
The Audio for that file.
Definition at line 83 of file audio_system.cpp.
References Configure().
Referenced by PlayerFile::Load().
 {
     auto source = new AudioSource(path);
     AudioSink::StreamConfigurator config_fn = std::bind(
                     &AudioSystem::Configure, this, source->ChannelCount(),
                     source->OutputSampleFormat(), source->SampleRate(),
                     source->BufferSampleCapacity(), std::placeholders::_1);
     auto sink = new AudioSink(config_fn, source->BytesPerSample());
     return new Audio(source, sink);
 }
const portaudio::Device & AudioSystem::PaDeviceFrom (const std::string & id_string) const private
Converts a string device ID to a PortAudio device.
Parameters
id_string The device ID, as a string.
Returns
The device.
Definition at line 115 of file audio_system.cpp.
References MSG_DEV_BADID.
Referenced by Configure().
 {
     auto &pa = portaudio::System::instance();
     PaDeviceIndex id_pa = 0;
     std::istringstream is(id_string);
     is >> id_pa;
     if (id_pa >= pa.deviceCount()) {
         throw ConfigError(MSG_DEV_BADID);
     }
     return pa.deviceByIndex(id_pa);
 }
portaudio::SampleDataFormat AudioSystem::PaSampleFormatFrom (SampleFormat fmt) const private
Converts a sample format identifier from playd to PortAudio.
Parameters
fmt The playd sample format identifier.
Returns
The PortAudio equivalent of the given SampleFormat.
Definition at line 140 of file audio_system.cpp.
References MSG_DECODE_BADRATE.
Referenced by Configure().
 {
     try
     {
         return pa_from_sf.at(fmt);
     }
     catch (std::out_of_range)
     {
         throw FileError(MSG_DECODE_BADRATE);
     }
 }
void AudioSystem::SetDeviceID (int id)
Sets the current device ID.
Parameters
id The device ID to use for subsequent Audios.
Definition at line 78 of file audio_system.cpp.
References device_id.
Referenced by playd::Run().
 {
     this->device_id = std::to_string(id);
 }
The documentation for this class was generated from the following files:
src/audio/audio_system.hpp
src/audio/audio_system.cpp