URY playd: IoReactor Class Reference
IoReactor Class Reference
The IO reactor, which services input, routes responses, and executes the Player update routine periodically.
#include <io_reactor.hpp>
Public Member Functions
IoReactor (Player &player, CommandHandler &handler, const std::string &address, const std::string &port)
Constructs an IoReactor.
IoReactor (const IoReactor &)=delete
Deleted copy constructor.
IoReactor & operator= (const IoReactor &)=delete
Deleted copy-assignment.
void Run ()
Runs the reactor.
void End ()
Ends the reactor.
void NewConnection (uv_stream_t *server)
Accepts a new connection.
void RemoveConnection (TcpResponseSink &sink)
Removes a connection.
Public Member Functions inherited from ResponseSink
void Respond (ResponseCode code, const std::string &message) const
Outputs a response.
void RespondWithError (const Error &error) const
Emits an error as a response.
Private Member Functions
void RespondRaw (const std::string &string) const override
Outputs a raw response string.
void InitAcceptor (const std::string &address, const std::string &port)
Initialises a TCP acceptor on the given address and port.
void DoUpdateTimer ()
Sets up a periodic timer to run the playd update loop.
Private Attributes
std::set< std::shared_ptr
< TcpResponseSink > > connections
The set of connections currently serviced by the IoReactor.
uv_tcp_t server
The libuv handle for the TCP server.
uv_timer_t updater
The libuv handle for the update timer.
Player & player
The player.
CommandHandler & handler
The command handler.
Static Private Attributes
static const uint16_t PLAYER_UPDATE_PERIOD = 5
The period between player updates.
Additional Inherited Members
Public Types inherited from ResponseSink
using Callback = std::function< void(ResponseSink &)>
A type for callbacks taking a ResponseSink.
Detailed Description
The IO reactor, which services input, routes responses, and executes the Player update routine periodically.
Definition at line 35 of file io_reactor.hpp.
Constructor & Destructor Documentation
IoReactor::IoReactor (Player & player, CommandHandler & handler, const std::string & address, const std::string & port) explicit
Constructs an IoReactor.
Parameters
player The player to which periodic update requests shall be sent.
handler The handler to which command inputs shall be sent.
address The address to which IoReactor will bind.
port The port on which IoReactor will listen for clients.
Definition at line 138 of file io_reactor.cpp.
References DoUpdateTimer(), and InitAcceptor().
     : player(player), handler(handler)
 {
     InitAcceptor(address, port);
     DoUpdateTimer();
 }
Member Function Documentation
void IoReactor::End ()
Ends the reactor.
This should be called by the parent object when the player is quitting.
Definition at line 183 of file io_reactor.cpp.
 {
     uv_stop(uv_default_loop());
 }
void IoReactor::InitAcceptor (const std::string & address, const std::string & port) private
Initialises a TCP acceptor on the given address and port.
Parameters
address The IPv4 address on which the TCP server should listen.
port The TCP port on which the TCP server should listen.
Definition at line 159 of file io_reactor.cpp.
References server, and UvListenCallback().
Referenced by IoReactor().
 {
     int uport = std::stoi(port);
     uv_tcp_init(uv_default_loop(), &this->server);
     this->server.data = static_cast<void *>(this);
     struct sockaddr_in bind_addr;
     uv_ip4_addr(address.c_str(), uport, &bind_addr);
     uv_tcp_bind(&this->server, (const sockaddr *)&bind_addr, 0);
     // TODO: Handle errors from uv_listen.
     uv_listen((uv_stream_t *)&this->server, 128, UvListenCallback);
     Debug() << "Listening at" << address << "on" << port << std::endl;
 }
void IoReactor::NewConnection (uv_stream_t * server)
Accepts a new connection.
This accepts the connection, and adds it to this IoReactor's connection pool.
This should be called with a server that has just received a new connection.
Parameters
server Pointer to the libuv server accepting connections.
Todo:
This isn't a great fit for the public interface of IoReactor - separate into a ConnectionPool class?
Definition at line 114 of file io_reactor.cpp.
References connections, handler, player, UvAlloc(), UvCloseCallback(), UvReadCallback(), and Player::WelcomeClient().
Referenced by UvListenCallback().
 {
     uv_tcp_t *client = new uv_tcp_t();
     uv_tcp_init(uv_default_loop(), client);
     if (uv_accept(server, (uv_stream_t *)client) == 0) {
         Debug() << "New connection" << std::endl;
         auto tcp = std::make_shared<TcpResponseSink>(*this, client,
                                                      this->handler);
         this->player.WelcomeClient(*tcp);
         this->connections.insert(tcp);
         client->data = static_cast<void *>(tcp.get());
         uv_read_start((uv_stream_t *)client, UvAlloc, UvReadCallback);
     } else {
         uv_close((uv_handle_t *)client, UvCloseCallback);
     }
 }
void IoReactor::RemoveConnection (TcpResponseSink & sink)
Removes a connection.
Parameters
sink The connection to remove.
Todo:
Rename sink?
This isn't a great fit for the public interface of IoReactor - separate into a ConnectionPool class?
Definition at line 133 of file io_reactor.cpp.
References connections.
Referenced by TcpResponseSink::Close().
 {
     this->connections.erase(std::make_shared<TcpResponseSink>(conn));
 }
void IoReactor::RespondRaw (const std::string & string) const override private virtual
Outputs a raw response string.
Parameters
string The response string, of the form "CODE message".
Implements ResponseSink.
Definition at line 176 of file io_reactor.cpp.
References connections.
 {
     for (const auto &conn : this->connections) {
         conn->RespondRaw(string);
     }
 }
void IoReactor::Run ()
Runs the reactor.
It will block until terminated.
Definition at line 146 of file io_reactor.cpp.
 {
     uv_run(uv_default_loop(), UV_RUN_DEFAULT);
 }
The documentation for this class was generated from the following files:
src/io/io_reactor.hpp
src/io/io_reactor.cpp