URY playd: Tokeniser Class Reference
Tokeniser Class Reference
A string tokeniser.
#include <tokeniser.hpp>
Public Member Functions
Tokeniser (CommandHandler &handler, ResponseSink &response_sink)
Constructs a new Tokeniser.
void Feed (const char *start, unsigned int nread)
Feeds the contents of a character buffer into a Tokeniser.
Private Types
enum QuoteType : std::uint8_t { QuoteType::NONE, QuoteType::SINGLE, QuoteType::DOUBLE }
Enumeration of quotation types.
Private Member Functions
void Emit ()
Finishes the current word and sends the line to the CommandHandler.
void EndWord ()
Finishes the current word, adding it to the tokenised line.
void Push (unsigned char c)
Pushes a raw character onto the end of the current word.
Private Attributes
CommandHandler & handler
The command handler to which complete lines should be sent.
ResponseSink & response_sink
The response sink to which command acknowledgements should be sent.
bool escape_next_character
Whether the next character is to be interpreted as an escape code.
QuoteType quote_type
The type of quotation currently being used in this Tokeniser.
std::vector< std::string > words
The current vector of completed, tokenised words.
std::string current_word
The current, incomplete word to which new characters should be added.
Detailed Description
A string tokeniser.
A Tokeniser is fed chunks of incoming data from the IO system, and emits any fully-formed command lines it encounters to the command handler.
See also
CommandHandler
IoReactor
Definition at line 25 of file tokeniser.hpp.
Member Enumeration Documentation
enum Tokeniser::QuoteType : std::uint8_t strong private
Enumeration of quotation types.
Enumerator
NONE
Not currently in a quote pair.
SINGLE
In single quotes ('').
DOUBLE
In double quotes ("").
Definition at line 45 of file tokeniser.hpp.
                          : std::uint8_t {
         NONE,
         SINGLE,
         DOUBLE
     };
Constructor & Destructor Documentation
Tokeniser::Tokeniser (CommandHandler & handler, ResponseSink & response_sink)
Constructs a new Tokeniser.
Parameters
handler The command handler to which full commands should be sent.
response_sink The response sink to which errors and acknowledgements should be sent.
Definition at line 18 of file tokeniser.cpp.
     : handler(handler),
       response_sink(response_sink),
       escape_next_character(false),
       quote_type(Tokeniser::QuoteType::NONE)
 {
 }
Member Function Documentation
void Tokeniser::Feed (const char * start, unsigned int nread)
Feeds the contents of a character buffer into a Tokeniser.
Parameters
start The pointer to the start of the character buffer.
nread The number of elements in the character buffer.
Definition at line 26 of file tokeniser.cpp.
References DOUBLE, Emit(), EndWord(), escape_next_character, NONE, Push(), quote_type, and SINGLE.
Referenced by TcpResponseSink::Read().
 {
     for (unsigned int i = 0; i < nread; i++) {
         unsigned char c = start[i];
         if (this->escape_next_character) {
             Push(c);
             continue;
         }
         switch (this->quote_type) {
             case QuoteType::SINGLE:
                 if (c == '\'') {
                     this->quote_type = QuoteType::NONE;
                 } else {
                     Push(c);
                 }
                 break;
             case QuoteType::DOUBLE:
                 switch (c) {
                     case '\"':
                         this->quote_type =
                                         QuoteType::NONE;
                         break;
                     case '\\':
                         this->escape_next_character =
                                         true;
                         break;
                     default:
                         Push(c);
                         break;
                 }
                 break;
             case QuoteType::NONE:
                 switch (c) {
                     case '\n':
                         Emit();
                         break;
                     case '\'':
                         this->quote_type = QuoteType::
                                         SINGLE;
                         break;
                     case '\"':
                         this->quote_type = QuoteType::
                                         DOUBLE;
                         break;
                     case '\\':
                         this->escape_next_character =
                                         true;
                         break;
                     default:
                         isspace(c) ? EndWord()
                                    : Push(c);
                         break;
                 }
                 break;
         }
     }
 }
void Tokeniser::Push (unsigned char c) private
Pushes a raw character onto the end of the current word.
This also clears the escape_next_character flag.
Parameters
c The character to push onto the current word.
Definition at line 94 of file tokeniser.cpp.
References current_word, escape_next_character, NONE, and quote_type.
Referenced by Feed().
 {
     assert(this->escape_next_character ||
            !(this->quote_type == QuoteType::NONE && isspace(c)));
     this->current_word.push_back(c);
     this->escape_next_character = false;
     assert(!this->current_word.empty());
 }
Member Data Documentation
std::string Tokeniser::current_word private
The current, incomplete word to which new characters should be added.
Definition at line 70 of file tokeniser.hpp.
Referenced by Emit(), EndWord(), and Push().
bool Tokeniser::escape_next_character private
Whether the next character is to be interpreted as an escape code.
This usually gets set to true when a backslash is detected.
Definition at line 60 of file tokeniser.hpp.
Referenced by Emit(), Feed(), and Push().
ResponseSink& Tokeniser::response_sink private
The response sink to which command acknowledgements should be sent.
This includes OKAY (successful command) and WHAT (bad command).
Definition at line 56 of file tokeniser.hpp.
Referenced by Emit().
The documentation for this class was generated from the following files:
src/io/tokeniser.hpp
src/io/tokeniser.cpp