URY playd: CommandHandler Class Reference
CommandHandler Class Reference
The playd command handler.
#include <cmd.hpp>
Public Types
typedef std::vector< std::string > WordList
The type of lists of command words.
Public Member Functions
CommandHandler (Player &player)
Constructs a CommandHandler.
CommandResult Handle (const WordList &words)
Handles a command line.
Private Member Functions
CommandResult RunNullary (const std::string &cmd)
Runs a nullary (0-argument) command.
CommandResult RunUnary (const std::string &cmd, const std::string &arg)
Runs a unary (1-argument) command.
Private Attributes
Player & player
Reference to the Player on which commands run.
Detailed Description
The playd command handler.
Definition at line 27 of file cmd.hpp.
Constructor & Destructor Documentation
CommandHandler::CommandHandler (Player & player)
Constructs a CommandHandler.
Parameters
player A reference to the Player on which the playd commands will run.
Definition at line 19 of file cmd.cpp.
                                              : player(player)
 {
 }
Member Function Documentation
CommandResult CommandHandler::Handle (const WordList & words)
Handles a command line.
Parameters
words A reference to the list of words in the command.
Returns
Whether the command succeeded.
Definition at line 23 of file cmd.cpp.
References CommandResult::Invalid(), MSG_CMD_INVALID, RunNullary(), and RunUnary().
Referenced by Connection::HandleCommand().
 {
     if (words.size() == 1) return this->RunNullary(words[0]);
     if (words.size() == 2 && !words[1].empty())
         return this->RunUnary(words[0], words[1]);
     return CommandResult::Invalid(MSG_CMD_INVALID);
 }
CommandResult CommandHandler::RunNullary (const std::string & cmd) private
Runs a nullary (0-argument) command.
Parameters
cmd The command word.
Returns
True if the command was successfully found and executed; false otherwise.
Definition at line 33 of file cmd.cpp.
References Player::Eject(), CommandResult::Invalid(), MSG_CMD_INVALID, Player::Play(), player, Player::Quit(), and Player::Stop().
Referenced by Handle().
 {
     if ("play" == cmd) return this->player.Play();
     if ("stop" == cmd) return this->player.Stop();
     if ("eject" == cmd) return this->player.Eject();
     if ("quit" == cmd) return this->player.Quit();
     return CommandResult::Invalid(MSG_CMD_INVALID);
 }
CommandResult CommandHandler::RunUnary (const std::string & cmd, const std::string & arg) private
Runs a unary (1-argument) command.
Parameters
cmd The command word.
arg The argument to the command.
Returns
True if the command was successfully found and executed; false otherwise.
Definition at line 43 of file cmd.cpp.
References CommandResult::Invalid(), Player::Load(), MSG_CMD_INVALID, player, and Player::Seek().
Referenced by Handle().
 {
     if ("load" == cmd) return this->player.Load(arg);
     if ("seek" == cmd) return this->player.Seek(arg);
     return CommandResult::Invalid(MSG_CMD_INVALID);
 }
The documentation for this class was generated from the following files:
src/cmd.hpp
src/cmd.cpp