URY playd: RingBuffer< RepT, SampleCountT > Class Template Reference
RingBuffer< RepT, SampleCountT > Class Template Reference
A ring buffer.
#include <ringbuffer.hpp>
Public Member Functions
RingBuffer (int power, int size)
Constructs a RingBuffer.
~RingBuffer ()
Destructs a PaRingBuffer.
RingBuffer (const RingBuffer &)=delete
Deleted copy constructor.
RingBuffer & operator= (const RingBuffer &)=delete
Deleted copy-assignment.
SampleCountT WriteCapacity () const
The current write capacity.
SampleCountT ReadCapacity () const
The current read capacity.
SampleCountT Write (RepT *start, SampleCountT count)
Writes samples from an array into the ring buffer.
SampleCountT Read (RepT *start, SampleCountT count)
Reads samples from the ring buffer into an array.
void Flush ()
Empties the ring buffer.
Private Member Functions
SampleCountT CountCast (ring_buffer_size_t count) const
Converts a ring buffer size into an external size.
Private Attributes
char * buffer
The array used by the ringbuffer.
PaUtilRingBuffer * rb
The internal PortAudio ringbuffer.
Detailed Description
template<typename RepT, typename SampleCountT>
class RingBuffer< RepT, SampleCountT >
A ring buffer.
This ring buffer is based on the PortAudio ring buffer, provided in the contrib/ directory. This is stable and performs well, but, as it is C code, necessitates some hoop jumping to integrate and could do with being replaced with a native solution.
Definition at line 30 of file ringbuffer.hpp.
Constructor & Destructor Documentation
template<typename RepT, typename SampleCountT> RingBuffer< RepT, SampleCountT >::RingBuffer (int power, int size) inline
Constructs a RingBuffer.
Precondition: 0 < power, 0 < size.
Postcondition: The RingBuffer is fully initialised.
Parameters
power n, where 2^n is the number of elements in the ring buffer.
size The size of one element in the ring buffer.
Definition at line 42 of file ringbuffer.hpp.
     {
         assert(0 < power);
         assert(0 < size);
         this->rb = new PaUtilRingBuffer;
         this->buffer = new char[(1 << power) * size];
         int init_result = PaUtil_InitializeRingBuffer(
                         this->rb, size,
                         static_cast<ring_buffer_size_t>(1 << power),
                         this->buffer);
         if (init_result != 0) {
             throw new InternalError(MSG_OUTPUT_RINGINIT);
         }
         assert(this->rb != nullptr);
         assert(this->buffer != nullptr);
     }
Member Function Documentation
template<typename RepT, typename SampleCountT> SampleCountT RingBuffer< RepT, SampleCountT >::CountCast (ring_buffer_size_t count) const inline private
Converts a ring buffer size into an external size.
Parameters
count The size/count in PortAudio form.
Returns
The size/count after casting to SampleCountT.
Definition at line 174 of file ringbuffer.hpp.
Referenced by RingBuffer< char, unsigned long >::Read(), RingBuffer< char, unsigned long >::ReadCapacity(), RingBuffer< char, unsigned long >::Write(), and RingBuffer< char, unsigned long >::WriteCapacity().
     {
         return static_cast<SampleCountT>(count);
     }
template<typename RepT, typename SampleCountT> SampleCountT RingBuffer< RepT, SampleCountT >::Read (RepT * start, SampleCountT count) inline
Reads samples from the ring buffer into an array.
To read one sample, pass a count of 1 and take a pointer to the sample variable.
Precondition: start points to a valid array, 0 < count <= the size of the block of memory pointed to by start, count <= ReadCapacity().
Postcondition: The block of memory pointed to by start and bounded by count and ReadCapacity() has been filled with the appropriate number of samples from the front of the ring buffer.
Parameters
start The start of the array buffer to which we write samples. Must not be nullptr.
count The number of samples to read. This must not exceed the minimum of ReadCapacity() and the length of the array.
Returns
The number of samples read, which should not exceed count.
See also
ReadCapacity
Definition at line 149 of file ringbuffer.hpp.
Referenced by AudioSink::ReadSamplesToOutput().
     {
         assert(0 < count);
         assert(count <= ReadCapacity());
         return CountCast(PaUtil_ReadRingBuffer(
                         this->rb, start,
                         static_cast<ring_buffer_size_t>(count)));
     }
template<typename RepT, typename SampleCountT> SampleCountT RingBuffer< RepT, SampleCountT >::ReadCapacity () const inline
The current read capacity.
Returns
The number of samples available in this ring buffer.
See also
Read
Definition at line 93 of file ringbuffer.hpp.
Referenced by AudioSink::PlayCallbackStep(), and RingBuffer< char, unsigned long >::Read().
     {
         return CountCast(PaUtil_GetRingBufferReadAvailable(this->rb));
     }
template<typename RepT, typename SampleCountT> SampleCountT RingBuffer< RepT, SampleCountT >::Write (RepT * start, SampleCountT count) inline
Writes samples from an array into the ring buffer.
To write one sample, pass a count of 1 and take a pointer to the sample variable. Note that start pointer is not constant. This is because the underlying implementation of the ring buffer might not guarantee that the array is left untouched.
Precondition: start points to a valid array, 0 < count <= the size of the block of memory pointed to by start, count <= WriteCapacity().
Postcondition: The ringbuffer has been written to with the contents of the memory pointed to by start and bounded by count and WriteCapacity().
Parameters
start The start of the array buffer from which we read samples. Must not be nullptr.
count The number of samples to write. This must not exceed the minimum of WriteCapacity() and the length of the array.
Returns
The number of samples written, which should not exceed count.
See also
WriteCapacity
Definition at line 120 of file ringbuffer.hpp.
Referenced by AudioSink::Transfer().
     {
         assert(0 < count);
         assert(count <= WriteCapacity());
         return CountCast(PaUtil_WriteRingBuffer(
                         this->rb, start,
                         static_cast<ring_buffer_size_t>(count)));
     }
template<typename RepT, typename SampleCountT> SampleCountT RingBuffer< RepT, SampleCountT >::WriteCapacity () const inline
The current write capacity.
Returns
The number of samples this ring buffer has space to store.
See also
Write
Definition at line 83 of file ringbuffer.hpp.
Referenced by AudioSink::Transfer(), and RingBuffer< char, unsigned long >::Write().
     {
         return CountCast(PaUtil_GetRingBufferWriteAvailable(this->rb));
     }
The documentation for this class was generated from the following file:
src/audio/ringbuffer.hpp