URY playd: ConnectionPool Class Reference
ConnectionPool Class Reference
A pool of TCP connections.
#include <io_core.hpp>
Public Member Functions
ConnectionPool (Player &player, CommandHandler &handler)
Constructs a ConnectionPool.
void Accept (uv_stream_t *server)
Accepts a new connection.
void Remove (Connection &conn)
Removes a connection.
void Broadcast (const std::string &message) const
Broadcasts a message to all connections.
Public Member Functions inherited from ResponseSink
void Respond (ResponseCode code, const std::string &message) const
Outputs a response with a single message argument.
void RespondArgs (ResponseCode code, const std::vector< std::string > &arguments) const
Outputs a response with multiple message arguments.
Private Member Functions
void RespondRaw (const std::string &string) const override
Outputs a raw response string.
Private Attributes
Player & player
The player.
CommandHandler & handler
The command handler.
std::vector< std::unique_ptr
< Connection > > connections
The set of connections inside this ConnectionPool.
Additional Inherited Members
Detailed Description
A pool of TCP connections.
Definition at line 30 of file io_core.hpp.
Constructor & Destructor Documentation
ConnectionPool::ConnectionPool (Player & player, CommandHandler & handler)
Constructs a ConnectionPool.
Parameters
player The player that forms welcome responses for new clients.
handler The handler to which read commands should be sent.
Definition at line 114 of file io_core.cpp.
     : player(player), handler(handler), connections()
 {
 }
Member Function Documentation
void ConnectionPool::Accept (uv_stream_t * server)
Accepts a new connection.
This accepts the connection, and adds it to this IoCore's connection pool.
This should be called with a server that has just received a new connection.
Parameters
server Pointer to the libuv server accepting connections.
Definition at line 119 of file io_core.cpp.
References connections, handler, player, UvAlloc(), UvCloseCallback(), UvReadCallback(), and Player::WelcomeClient().
Referenced by UvListenCallback().
 {
     uv_tcp_t *client = new uv_tcp_t();
     uv_tcp_init(uv_default_loop(), client);
     if (uv_accept(server, (uv_stream_t *)client) == 0) {
         this->connections.emplace_back(
                         new Connection(*this, client, this->handler));
         this->player.WelcomeClient(*this->connections.back());
         client->data = static_cast<void *>(
                         this->connections.back().get());
         uv_read_start((uv_stream_t *)client, UvAlloc, UvReadCallback);
     } else {
         uv_close((uv_handle_t *)client, UvCloseCallback);
     }
 }
void ConnectionPool::Broadcast (const std::string & message) const
Broadcasts a message to all connections.
Parameters
message The message to send to all connections.
Definition at line 147 of file io_core.cpp.
References connections.
Referenced by RespondRaw(), and IoCore::RespondRaw().
 {
     if (this->connections.empty()) return;
     Debug() << "Sending command:" << message << std::endl;
     for (const auto &conn : this->connections) conn->RespondRaw(message);
 }
void ConnectionPool::Remove (Connection & conn)
Removes a connection.
Parameters
conn The connection to remove.
Definition at line 138 of file io_core.cpp.
References connections.
Referenced by Connection::Depool().
 {
     this->connections.erase(std::remove_if(
                     this->connections.begin(), this->connections.end(),
                     [&](const std::unique_ptr<Connection> &p) {
                         return p.get() == &conn;
                 }));
 }
void ConnectionPool::RespondRaw (const std::string & string) const override private virtual
Outputs a raw response string.
Parameters
string The raw, escaped response string.
Implements ResponseSink.
Definition at line 155 of file io_core.cpp.
References Broadcast().
 {
     this->Broadcast(string);
 }
The documentation for this class was generated from the following files:
src/io/io_core.hpp
src/io/io_core.cpp