URY playd: AudioSource Class Reference
AudioSource Class Reference
An object responsible for decoding an audio file.
#include <audio_source.hpp>
Public Types
enum DecodeState : std::uint8_t { DecodeState::WAITING_FOR_FRAME, DecodeState::DECODING, DecodeState::END_OF_FILE }
An enumeration of possible states the decoder can be in.
using DecodeVector = std::vector< std::uint8_t >
Type of decoded sample vectors.
using DecodeResult = std::pair< DecodeState, DecodeVector >
Type of the result of Decode().
using SampleByteCount = int
Type for the count of bytes per sample.
Public Member Functions
AudioSource (const std::string &path)
Constructs an AudioSource.
~AudioSource ()
Destructs an AudioSource.
std::string Path () const
Gets the file-path of this audio source's audio file.
DecodeResult Decode ()
Performs a round of decoding.
std::uint8_t ChannelCount () const
Returns the channel count.
double SampleRate () const
Returns the sample rate.
SampleFormat OutputSampleFormat () const
Returns the output sample format.
size_t BufferSampleCapacity () const
Returns the number of samples this decoder's buffer can store.
size_t BytesPerSample () const
Returns the number of bytes for each sample this decoder outputs.
std::uint64_t Seek (std::chrono::microseconds position)
Seeks to the given position, in microseconds.
std::uint64_t SamplePositionFromMicroseconds (std::chrono::microseconds position) const
Converts a position in microseconds to an elapsed sample count.
std::chrono::microseconds MicrosecondPositionFromSamples (std::uint64_t samples) const
Converts an elapsed sample count to a position in microseconds.
Private Member Functions
void Open (const std::string &path)
Opens a new file for this AudioSource.
void Close ()
Closes the AudioSource's current file.
Private Attributes
DecodeState decode_state
The current state of decoding.
std::vector< uint8_t > buffer
The decoding buffer.
sox_format_t * context
Pointer to the SoX context associated with this source.
Static Private Attributes
static const size_t BUFFER_SIZE = 16384
The size of the internal decoding buffer, in bytes.
Detailed Description
An object responsible for decoding an audio file.
The AudioSource is an interface to the ffmpeg library, which represents all the ffmpeg state associated with one file. It can be polled to decode frames of audio data, which are returned as byte vectors.
Definition at line 32 of file audio_source.hpp.
Member Enumeration Documentation
enum AudioSource::DecodeState : std::uint8_t strong
An enumeration of possible states the decoder can be in.
Enumerator
WAITING_FOR_FRAME
The decoder is currently trying to acquire a frame.
DECODING
The decoder is currently decoding a frame.
END_OF_FILE
The decoder has run out of things to decode.
Definition at line 35 of file audio_source.hpp.
                            : std::uint8_t {
         WAITING_FOR_FRAME,
         DECODING,
         END_OF_FILE
     };
Constructor & Destructor Documentation
AudioSource::AudioSource (const std::string & path)
Constructs an AudioSource.
Parameters
path The path to the file to load and decode using this decoder.
Definition at line 34 of file audio_source.cpp.
References Open().
     : buffer(BUFFER_SIZE), context(nullptr)
 {
     Open(path);
 }
Member Function Documentation
size_t AudioSource::BufferSampleCapacity () const
Returns the number of samples this decoder's buffer can store.
Returns
The buffer sample capacity, in samples.
Definition at line 58 of file audio_source.cpp.
References buffer, and BytesPerSample().
Referenced by Decode().
 {
     return this->buffer.size() / this->BytesPerSample();
 }
size_t AudioSource::BytesPerSample () const
Returns the number of bytes for each sample this decoder outputs.
As the decoder returns packed samples, this includes the channel count as a factor.
Returns
The number of bytes per sample.
Definition at line 91 of file audio_source.cpp.
References ChannelCount(), and context.
Referenced by BufferSampleCapacity(), and Decode().
 {
     assert(this->context != nullptr);
     // Since libsox always outputs 32-bit samples, the bytes per sample is
     // always 4 per channel.
     // SoX has a slightly peculiar notion of sample counts, in that it
     // regards each channel as having its own separate sample, so we need
     // to multiply and divide sample counts by the channel count when
     // talking to SoX.
     return 4 * ChannelCount();
 }
std::uint8_t AudioSource::ChannelCount () const
Returns the channel count.
Returns
The number of channels this AudioSource is decoding.
Definition at line 52 of file audio_source.cpp.
References context.
Referenced by BytesPerSample(), Decode(), and Seek().
 {
     assert(this->context != nullptr);
     return this->context->signal.channels;
 }
AudioSource::DecodeResult AudioSource::Decode ()
Performs a round of decoding.
Returns
A pair of the decoder's state upon finishing the decoding round and the vector of bytes decoded. The vector may be empty, if the decoding round did not finish off a frame.
Definition at line 133 of file audio_source.cpp.
References buffer, BufferSampleCapacity(), BytesPerSample(), ChannelCount(), context, decode_state, DECODING, and END_OF_FILE.
 {
     assert(this->context != nullptr);
     auto buf = reinterpret_cast<sox_sample_t *>(&this->buffer.front());
     // See BytesPerSample() for an explanation of this ChannelCount().
     auto sox_capacity = BufferSampleCapacity() * ChannelCount();
     size_t read = sox_read(this->context, buf, sox_capacity);
     DecodeVector decoded;
     if (read == 0) {
         this->decode_state = DecodeState::END_OF_FILE;
     } else {
         this->decode_state = DecodeState::DECODING;
         // Copy only the bit of the buffer occupied by decoded data
         // See BytesPerSample() for an explanation of the
         // ChannelCount() division.
         auto front = this->buffer.begin();
         auto read_bytes = (BytesPerSample() * read) / ChannelCount();
         decoded = DecodeVector(front, front + read_bytes);
     }
     return std::make_pair(this->decode_state, decoded);
 }
std::chrono::microseconds AudioSource::MicrosecondPositionFromSamples (std::uint64_t samples) const
Converts an elapsed sample count to a position in microseconds.
Parameters
samples The number of elapsed samples.
Returns
The corresponding song position, in microseconds.
Definition at line 81 of file audio_source.cpp.
References SampleRate().
 {
     // This is basically SamplePositionFromMicroseconds but backwards.
     auto position_secs = std::chrono::seconds(samples) / SampleRate();
     return std::chrono::duration_cast<std::chrono::microseconds>(
                     position_secs);
 }
void AudioSource::Open (const std::string & path) private
Opens a new file for this AudioSource.
Parameters
path The absolute path to the audio file to load.
Definition at line 172 of file audio_source.cpp.
References Close(), and context.
Referenced by AudioSource(), and Seek().
 {
     Close();
     this->context = sox_open_read(path.c_str(), nullptr, nullptr, nullptr);
     if (this->context == nullptr) {
         std::ostringstream os;
         os << "couldn't open " << path;
         throw FileError(os.str());
     }
 }
SampleFormat AudioSource::OutputSampleFormat () const
Returns the output sample format.
Returns
The output sample format, as a SampleFormat.
The sample format of the data returned by this decoder.
Definition at line 164 of file audio_source.cpp.
References PACKED_SIGNED_INT_32.
 {
     // 'The function sox_read reads len samples in to buf using the format
     // handler specified by ft. All data read is converted to 32-bit signed
     // samples before being placed in to buf.'
     return SampleFormat::PACKED_SIGNED_INT_32;
 }
std::string AudioSource::Path () const
Gets the file-path of this audio source's audio file.
Returns
The audio file's path.
Definition at line 45 of file audio_source.cpp.
References context.
Referenced by Seek().
 {
     assert(this->context != nullptr);
     assert(this->context->filename != nullptr);
     return std::string(this->context->filename);
 }
std::uint64_t AudioSource::SamplePositionFromMicroseconds (std::chrono::microseconds position) const
Converts a position in microseconds to an elapsed sample count.
Parameters
position The song position, in microseconds.
Returns
The corresponding number of elapsed samples.
Definition at line 69 of file audio_source.cpp.
References SampleRate().
Referenced by Seek().
 {
     // The sample rate is expressed in terms of samples per second, so we
     // need to convert the position to seconds then multiply by the rate.
     // We do things in a slightly peculiar order to minimise rounding.
     auto sample_micros = usec * SampleRate();
     return std::chrono::duration_cast<std::chrono::seconds>(sample_micros)
                     .count();
 }
double AudioSource::SampleRate () const
Returns the sample rate.
Returns
The output sample rate (Hz) as a double-precision floating point.
Definition at line 63 of file audio_source.cpp.
References context.
Referenced by MicrosecondPositionFromSamples(), and SamplePositionFromMicroseconds().
 {
     assert(this->context != nullptr);
     return this->context->signal.rate;
 }
std::uint64_t AudioSource::Seek (std::chrono::microseconds position)
Seeks to the given position, in microseconds.
For convenience, the new position (in terms of samples) is returned.
Parameters
position The new position in the file, in microseconds.
Returns
The new position in the file, in samples.
Definition at line 105 of file audio_source.cpp.
References ChannelCount(), Close(), context, decode_state, DECODING, END_OF_FILE, MSG_SEEK_FAIL, Open(), Path(), and SamplePositionFromMicroseconds().
 {
     assert(this->context != nullptr);
     auto samples = SamplePositionFromMicroseconds(position);
     // See BytesPerSample() for an explanation of this ChannelCount().
     auto sox_samples = samples * ChannelCount();
     // libsox doesn't seem to like seeking into an ended file, so close
     // and re-open it first.
     if (this->decode_state == DecodeState::END_OF_FILE) {
         std::string path = Path();
         Close();
         Open(path);
     }
     if (sox_seek(this->context, sox_samples, SOX_SEEK_SET) != SOX_SUCCESS) {
         throw InternalError(MSG_SEEK_FAIL);
     }
     // Reset the decoder state, because otherwise the decoder will get very
     // confused.
     this->decode_state = DecodeState::DECODING;
     return samples;
 }
Member Data Documentation
DecodeState AudioSource::decode_state private
The current state of decoding.
See also
DecodeState
Definition at line 140 of file audio_source.hpp.
Referenced by Decode(), and Seek().
The documentation for this class was generated from the following files:
src/audio/audio_source.hpp
src/audio/audio_source.cpp