URY playd: PipeAudio Class Reference
PipeAudio Class Reference
A concrete implementation of Audio as a 'pipe'.
#include <audio.hpp>
Public Member Functions
PipeAudio (std::unique_ptr< AudioSource > src, std::unique_ptr< AudioSink > sink)
Constructs a PipeAudio from a source and a sink.
Audio::State Update () override
Performs an update cycle on this Audio.
const std::string & File () const override
This Audio's current file.
void SetPlaying (bool playing) override
Sets whether this Audio should be playing or not.
Audio::State CurrentState () const override
The state of this Audio.
void SetPosition (std::uint64_t position) override
Attempts to seek to the given position.
std::uint64_t Position () const override
This Audio's current position.
Public Member Functions inherited from Audio
virtual ~Audio ()=default
Virtual, empty destructor for Audio.
Private Member Functions
void ClearFrame ()
Clears the current frame and its iterator.
bool DecodeIfFrameEmpty ()
Decodes a new frame, if the current frame is empty.
bool FrameFinished () const
Returns whether the current frame has been finished.
void TransferFrame ()
Transfers as much of the current frame as possible to the sink.
Private Attributes
std::unique_ptr< AudioSource > src
The source of audio data.
std::unique_ptr< AudioSink > sink
The sink to which audio data is sent.
AudioSource::DecodeVector frame
The current decoded frame.
AudioSource::DecodeVector::iterator frame_iterator
The current position in the current decoded frame.
Additional Inherited Members
Public Types inherited from Audio
enum State : uint8_t { State::NONE, State::STOPPED, State::PLAYING, State::AT_END }
Enumeration of possible states for this Audio.
Detailed Description
A concrete implementation of Audio as a 'pipe'.
PipeAudio is comprised of a 'source', which decodes frames from a file, and a 'sink', which plays out the decoded frames. Updating consists of shifting frames from the source to the sink.
See also
Audio
AudioSink
AudioSource
Definition at line 147 of file audio.hpp.
Constructor & Destructor Documentation
PipeAudio()
PipeAudio::PipeAudio (std::unique_ptr< AudioSource > src, std::unique_ptr< AudioSink > sink)
Constructs a PipeAudio from a source and a sink.
Parameters
src The source of decoded audio frames.
sink The target of decoded audio frames.
See also
AudioSystem::Load
Definition at line 62 of file audio.cpp.
References ClearFrame().
     : src(std::move(src)), sink(std::move(sink))
 {
     this->ClearFrame();
 }
Member Function Documentation
CurrentState()
Audio::State PipeAudio::CurrentState () const override virtual
The state of this Audio.
Returns
this Audio's current state.
Implements Audio.
Definition at line 85 of file audio.cpp.
References sink.
 {
     return this->sink->State();
 }
DecodeIfFrameEmpty()
bool PipeAudio::DecodeIfFrameEmpty () private
Decodes a new frame, if the current frame is empty.
Returns
True if more frames are available to decode; false otherwise.
Definition at line 153 of file audio.cpp.
References AudioSource::END_OF_FILE, frame, frame_iterator, FrameFinished(), and src.
Referenced by Update().
 {
     // Either the current frame is in progress, or has been emptied.
     // AdvanceFrameIterator() establishes this assertion by emptying a
     // frame as soon as it finishes.
     assert(this->frame.empty() || !this->FrameFinished());
     // If we still have a frame, don't bother decoding yet.
     if (!this->FrameFinished()) return true;
     assert(this->src != nullptr);
     AudioSource::DecodeResult result = this->src->Decode();
     this->frame = result.second;
     this->frame_iterator = this->frame.begin();
     return result.first != AudioSource::DecodeState::END_OF_FILE;
 }
File()
const std::string & PipeAudio::File () const override virtual
This Audio's current file.
Returns
The filename of this current file.
Exceptions
NoAudioError if the current state is NONE.
Implements Audio.
Definition at line 69 of file audio.cpp.
References src.
 {
     return this->src->Path();
 }
FrameFinished()
bool PipeAudio::FrameFinished () const private
Returns whether the current frame has been finished.
If this is true, then either the frame is empty, or all of the samples in the frame have been fed to the ringbuffer.
Returns
True if the frame is finished; false otherwise.
Definition at line 172 of file audio.cpp.
References frame, and frame_iterator.
Referenced by DecodeIfFrameEmpty(), TransferFrame(), and Update().
 {
     return this->frame.end() <= this->frame_iterator;
 }
Position()
std::uint64_t PipeAudio::Position () const override virtual
This Audio's current position.
As this may be executing whilst the playing callback is running, do not expect it to be highly accurate.
Returns
The current position, in microseconds.
Exceptions
NoAudioError if the current state is NONE.
See also
Seek
Implements Audio.
Definition at line 90 of file audio.cpp.
References sink, and src.
 {
     assert(this->sink != nullptr);
     assert(this->src != nullptr);
     return this->src->MicrosFromSamples(this->sink->Position());
 }
SetPlaying()
void PipeAudio::SetPlaying (bool playing) override virtual
Sets whether this Audio should be playing or not.
Parameters
playing True for playing; false for stopped.
Exceptions
NoAudioError if the current state is NONE.
Implements Audio.
Definition at line 74 of file audio.cpp.
References sink.
 {
     assert(this->sink != nullptr);
     if (playing) {
         this->sink->Start();
     } else {
         this->sink->Stop();
     }
 }
SetPosition()
void PipeAudio::SetPosition (std::uint64_t position) override virtual
Attempts to seek to the given position.
Parameters
position The position to seek to, in microseconds.
Exceptions
NoAudioError if the current state is NONE.
See also
Position
Implements Audio.
Definition at line 98 of file audio.cpp.
References ClearFrame(), sink, and src.
 {
     assert(this->sink != nullptr);
     assert(this->src != nullptr);
     auto in_samples = this->src->SamplesFromMicros(position);
     auto out_samples = this->src->Seek(in_samples);
     this->sink->SetPosition(out_samples);
     // We might still have decoded samples from the old position in
     // our frame, so clear them out.
     this->ClearFrame();
 }
Update()
Audio::State PipeAudio::Update () override virtual
Performs an update cycle on this Audio.
Depending on the Audio implementation, this may do actions such as performing a decoding round, checking for end-of-file, transferring frames, and so on.
Returns
The state of the Audio after updating.
See also
State
Implements Audio.
Definition at line 118 of file audio.cpp.
References DecodeIfFrameEmpty(), FrameFinished(), sink, src, and TransferFrame().
 {
     assert(this->sink != nullptr);
     assert(this->src != nullptr);
     bool more_available = this->DecodeIfFrameEmpty();
     if (!more_available) this->sink->SourceOut();
     if (!this->FrameFinished()) this->TransferFrame();
     return this->sink->State();
 }
The documentation for this class was generated from the following files:
src/audio/audio.hpp
src/audio/audio.cpp