URY playd: Audio Class Reference
Audio Class Reference
An audio file.
#include <audio.hpp>
Public Member Functions
Audio (AudioSource *source, AudioSink *sink)
Constructs an Audio from a source and a sink.
std::string Path () const
Gets the file-path of this audio file.
void Start ()
Starts playback of this audio file.
void Stop ()
Stops playback of this audio file.
bool Update ()
Performs an update cycle on this Audio.
bool IsStopped ()
Checks to see if audio playback has stopped.
bool FrameFinished ()
Returns whether the current frame has been finished.
bool FileEnded ()
Returns whether the audio file has ended.
template<typename R >
R CurrentPosition ()
Return the current position, as a std::chrono::duration.
std::chrono::microseconds CurrentPositionMicroseconds ()
Gets the current played position in the song, in microseconds.
template<typename R >
void SeekToPosition (R position)
Seek to a position expressed as a std::chrono::duration.
void SeekToPositionMicroseconds (std::chrono::microseconds microseconds)
Attempts to seek to the given position in microseconds.
Private Member Functions
void ClearFrame ()
Clears the current frame and its iterator.
bool DecodeIfFrameEmpty ()
Decodes a new frame, if the current frame is empty.
void TransferFrame ()
Transfers as much of the current frame as possible to the sink.
Private Attributes
std::unique_ptr< AudioSource > source
The source of audio data.
std::unique_ptr< AudioSink > sink
The sink to which audio data is sent.
bool file_ended
Whether the current file has stopped decoding.
AudioSource::DecodeVector frame
The current decoded frame.
AudioSource::DecodeVector::iterator frame_iterator
The current position in the current decoded frame.
Detailed Description
An audio file.
Audio contains all state pertaining to the output of one file to one stream. It contains a source of audio data and a sink to which it should be sent.
Definition at line 37 of file audio.hpp.
Constructor & Destructor Documentation
Audio::Audio (AudioSource * source, AudioSink * sink)
Constructs an Audio from a source and a sink.
Parameters
source The source of decoded audio frames.
sink The target of decoded audio frames.
See also
AudioSystem::Load
Definition at line 22 of file audio.cpp.
References ClearFrame().
                                                  : source(source), sink(sink)
 {
     ClearFrame();
 }
Member Function Documentation
template<typename R > R Audio::CurrentPosition () inline
Return the current position, as a std::chrono::duration.
Returns
The current position in the audio.
Definition at line 105 of file audio.hpp.
References CurrentPositionMicroseconds().
     {
         return std::chrono::duration_cast<R>(
                         CurrentPositionMicroseconds());
     }
std::chrono::microseconds Audio::CurrentPositionMicroseconds ()
Gets the current played position in the song, in microseconds.
As this may be executing whilst the playing callback is running, do not expect it to be highly accurate.
Returns
The current position, in microseconds.
Definition at line 48 of file audio.cpp.
References sink, and source.
Referenced by CurrentPosition().
 {
     return this->source->MicrosecondPositionFromSamples(
                     this->sink->Position());
 }
bool Audio::DecodeIfFrameEmpty () private
Decodes a new frame, if the current frame is empty.
Returns
True if more frames are available to decode; false otherwise.
Definition at line 101 of file audio.cpp.
References AudioSource::END_OF_FILE, frame, frame_iterator, FrameFinished(), and source.
Referenced by Update().
 {
     // Either the current frame is in progress, or has been emptied.
     // AdvanceFrameIterator() establishes this assertion by emptying a
     // frame as soon as it finishes.
     assert(this->frame.empty() || !FrameFinished());
     bool more_frames_available = true;
     if (FrameFinished()) {
         AudioSource::DecodeResult result = this->source->Decode();
         this->frame = result.second;
         this->frame_iterator = this->frame.begin();
         more_frames_available = result.first !=
                                 AudioSource::DecodeState::END_OF_FILE;
     }
     return more_frames_available;
 }
bool Audio::FileEnded ()
Returns whether the audio file has ended.
This does NOT mean that playback has ended; the ring buffer may still have samples waiting to send to the audio library.
Returns
True if there is no audio left to decode; false otherwise.
Definition at line 123 of file audio.cpp.
References file_ended.
 {
     return this->file_ended;
 }
bool Audio::FrameFinished ()
Returns whether the current frame has been finished.
If this is true, then either the frame is empty, or all of the samples in the frame have been fed to the ringbuffer.
Returns
True if the frame is finished; false otherwise.
Definition at line 128 of file audio.cpp.
References frame, and frame_iterator.
Referenced by DecodeIfFrameEmpty(), TransferFrame(), and Update().
 {
     return this->frame.end() <= this->frame_iterator;
 }
bool Audio::IsStopped ()
Checks to see if audio playback has stopped.
Returns
True if the audio stream is inactive; false otherwise.
See also
Start
Stop
Definition at line 43 of file audio.cpp.
References sink.
 {
     return this->sink->IsStopped();
 }
std::string Audio::Path () const
Gets the file-path of this audio file.
Returns
The audio file's path.
Definition at line 27 of file audio.cpp.
References source.
 {
     assert(this->source != nullptr);
     return this->source->Path();
 }
template<typename R > void Audio::SeekToPosition (R position) inline
Seek to a position expressed as a std::chrono::duration.
Parameters
position The position to seek to in the audio.
Definition at line 124 of file audio.hpp.
References SeekToPositionMicroseconds().
     {
         SeekToPositionMicroseconds(std::chrono::duration_cast<
                         std::chrono::microseconds>(position));
     }
void Audio::SeekToPositionMicroseconds (std::chrono::microseconds microseconds)
Attempts to seek to the given position in microseconds.
Parameters
microseconds The position to seek to, in microseconds.
Definition at line 54 of file audio.cpp.
References ClearFrame(), sink, and source.
Referenced by SeekToPosition().
 {
     auto samples = this->source->Seek(microseconds);
     this->sink->SetPosition(samples);
     ClearFrame();
 }
void Audio::Start ()
Starts playback of this audio file.
See also
Stop
IsStopped
Definition at line 33 of file audio.cpp.
References sink.
 {
     this->sink->Start();
 }
void Audio::Stop ()
Stops playback of this audio file.
See also
Start
IsHalted
Definition at line 38 of file audio.cpp.
References sink.
 {
     this->sink->Stop();
 }
bool Audio::Update ()
Performs an update cycle on this Audio.
This ensures the ring buffer has output to offer to the sound driver. It does this by by asking the AudioSource to decode if necessary.
Returns
True if there is more output to send to the sound card; false otherwise.
Definition at line 68 of file audio.cpp.
References DecodeIfFrameEmpty(), file_ended, FrameFinished(), sink, and TransferFrame().
 {
     bool more_frames_available = DecodeIfFrameEmpty();
     if (!FrameFinished()) {
         TransferFrame();
     }
     this->sink->SetInputReady(more_frames_available);
     this->file_ended = !more_frames_available;
     return more_frames_available;
 }
The documentation for this class was generated from the following files:
src/audio/audio.hpp
src/audio/audio.cpp