URY playd: Response Class Reference
Response Class Reference
A response.
#include <response.hpp>
Public Types
enum Code : std::uint8_t {
Code::OHAI, Code::IAMA, Code::FLOAD, Code::EJECT,
Code::POS, Code::END, Code::PLAY, Code::STOP,
Code::ACK
}
Enumeration of all possible response codes.
Public Member Functions
Response (const std::string &tag, Response::Code code)
Constructs a Response with no arguments.
Response & AddArg (const std::string &arg)
Adds an argument to this Response.
std::string Pack () const
Packs the Response, converting it to a BAPS3 protocol message.
Static Public Member Functions
static Response Success (const std::string &tag)
Shortcut for constructing a final response to a successful request.
static Response Invalid (const std::string &tag, const std::string &msg)
Shortcut for constructing a final response to a invalid request.
static Response Failure (const std::string &tag, const std::string &msg)
Shortcut for constructing a final response to a failed request.
Static Public Attributes
static const std::string NOREQUEST = "!"
The tag for unsolicited messages (not from responses).
static constexpr std::uint8_t CODE_COUNT = 9
The number of codes, which should agree with Response::Code.
Static Private Member Functions
static std::string EscapeArg (const std::string &arg)
Escapes a single response argument.
Private Attributes
std::string string
The current packed form of the response.
Static Private Attributes
static const std::array< std::string, CODE_COUNT > STRINGS
A map from Response::Code codes to their string equivalents.
Detailed Description
A response.
Definition at line 23 of file response.hpp.
Member Enumeration Documentation
Code
enum Response::Code : std::uint8_t strong
Enumeration of all possible response codes.
Note
If you're adding new responses here, update Response::STRINGS.
See also
Response::STRINGS
Enumerator
OHAI
Server starting up.
IAMA
Server sending its role.
FLOAD
The loaded file just changed.
EJECT
The loaded file just ejected.
POS
Server sending current song time.
END
The loaded file just ended.
PLAY
The loaded file is playing.
STOP
The loaded file has stopped.
ACK
Command result.
Definition at line 35 of file response.hpp.
                     : std::uint8_t {
         OHAI,
         IAMA,
         FLOAD,
         EJECT,
         POS,
         END,
         PLAY,
         STOP,
         ACK
     };
Constructor & Destructor Documentation
Response()
Response::Response (const std::string & tag, Response::Code code)
Constructs a Response with no arguments.
Parameters
tag The tag of the response.
code The Response::Code representing the response command.
Definition at line 32 of file response.cpp.
References EscapeArg(), and STRINGS.
Referenced by Failure(), Invalid(), and Success().
 {
     this->string = Response::EscapeArg(tag) + " " +
                    STRINGS[static_cast<uint8_t>(code)];
 }
Member Function Documentation
AddArg()
Response & Response::AddArg (const std::string & arg)
Adds an argument to this Response.
Parameters
arg The argument to add. The argument must not be escaped.
Returns
A reference to this Response, for chaining.
Definition at line 38 of file response.cpp.
References EscapeArg().
 {
     this->string += " " + Response::EscapeArg(arg);
     return *this;
 }
EscapeArg()
std::string Response::EscapeArg (const std::string & arg) static private
Escapes a single response argument.
Parameters
arg The argument to escape.
Returns
The escaped argument.
Definition at line 68 of file response.cpp.
Referenced by AddArg(), and Response().
 {
     bool escaping = false;
     std::string escaped;
     for (char c : arg) {
         // These are the characters (including all whitespace, via
         // isspace())  whose presence means we need to single-quote
         // escape the argument.
         bool is_escaper = c == '"' || c == '\'' || c == '\\';
         if (isspace(c) || is_escaper) escaping = true;
         // Since we use single-quote escaping, the only thing we need
         // to escape by itself is single quotes, which are replaced by
         // the sequence '\'' (break out of single quotes, escape a
         // single quote, then re-enter single quotes).
         escaped += (c == '\'') ? R"('\'')" : std::string(1, c);
     }
     // Only single-quote escape if necessary.
     // Otherwise, it wastes two characters!
     if (escaping) return "'" + escaped + "'";
     return escaped;
 }
Failure()
Response Response::Failure (const std::string & tag, const std::string & msg) static
Shortcut for constructing a final response to a failed request.
Parameters
tag The tag of the original request.
msg The failure message.
Returns
A Response acknowledging a failed request.
Definition at line 62 of file response.cpp.
References ACK, and Response().
Referenced by Player::Dump(), Player::Eject(), Player::End(), Player::Load(), Player::Pos(), Player::Quit(), and Player::SetPlaying().
 {
     return Response(tag, Response::Code::ACK).AddArg("FAIL").AddArg(msg);
 }
Invalid()
Response Response::Invalid (const std::string & tag, const std::string & msg) static
Shortcut for constructing a final response to a invalid request.
Parameters
tag The tag of the original request.
msg The failure message.
Returns
A Response acknowledging an invalid request.
Definition at line 56 of file response.cpp.
References ACK, and Response().
Referenced by Player::Load(), Player::Pos(), Connection::RunCommand(), and Player::SetPlaying().
 {
     return Response(tag, Response::Code::ACK).AddArg("WHAT").AddArg(msg);
 }
Pack()
std::string Response::Pack () const
Packs the Response, converting it to a BAPS3 protocol message.
Pack()ing does not alter the Response, which may be Pack()ed again.
Returns
The BAPS3 message, sans newline, ready to send.
Definition at line 44 of file response.cpp.
References string.
Referenced by IoCore::Broadcast(), Connection::Respond(), and IoCore::Unicast().
 {
     return this->string;
 }
Success()
Response Response::Success (const std::string & tag) static
Shortcut for constructing a final response to a successful request.
Parameters
tag The tag of the original request.
Returns
A Response acknowledging a successful request.
Definition at line 49 of file response.cpp.
References ACK, and Response().
Referenced by IoCore::Accept(), Player::Dump(), Player::Eject(), Player::End(), Player::Load(), Player::Pos(), Player::Quit(), and Player::SetPlaying().
 {
     return Response(tag, Response::Code::ACK)
             .AddArg("OK")
             .AddArg("success");
 }
Member Data Documentation
string
std::string Response::string private
The current packed form of the response.
See also
Pack
Definition at line 111 of file response.hpp.
Referenced by Pack().
STRINGS
const std::array< std::string, Response::CODE_COUNT > Response::STRINGS static private
Initial value:
{{
        "OHAI",
        "IAMA",
        "FLOAD",
        "EJECT",
        "POS",
        "END",
        "PLAY",
        "STOP",
        "ACK"
}}
A map from Response::Code codes to their string equivalents.
See also
Response::Code
Definition at line 100 of file response.hpp.
Referenced by Response().
The documentation for this class was generated from the following files:
src/response.hpp
src/response.cpp