URY playd: Playd Class Reference
Playd Class Reference
The playd application.
#include <main.hpp>
Public Member Functions
Playd (int argc, char *argv[])
Constructs an application instance, initialising its libraries.
int Run ()
Runs playd.
Public Member Functions inherited from ResponseSink
void Respond (ResponseCode code, const std::string &message) const
Outputs a response with a single message argument.
void RespondArgs (ResponseCode code, const std::vector< std::string > &arguments) const
Outputs a response with multiple message arguments.
Private Member Functions
void RespondRaw (const std::string &string) const override
Outputs a raw response string.
int GetDeviceID ()
Tries to get the output device ID from program arguments.
Private Attributes
std::vector< std::string > argv
The argument vector.
PaSoxAudioSystem audio
The audio subsystem.
PlayerFile pfile
The player-file subsystem.
PlayerPosition pposition
The player-position subsystem.
PlayerState pstate
The player-state subsystem.
Player player
The player subsystem.
CommandHandler handler
The command handler.
std::unique_ptr< IoCore > io
The I/O handler.
Static Private Attributes
static const std::uint64_t POSITION_PERIOD = 500000
The period between position announcements from the Player object.
static const int INVALID_ID = -1
The ID returned by GetDeviceID if something goes wrong.
Additional Inherited Members
Detailed Description
The playd application.
This class contains all the state required by playd, with the exception of that introduced by external C libraries. It is a RAII class, so constructing Playd will load playd's library dependencies, and destructing it will unload them. It is probably not safe to create more than one Playd.
Definition at line 31 of file main.hpp.
Constructor & Destructor Documentation
Playd::Playd (int argc, char * argv[])
Constructs an application instance, initialising its libraries.
Parameters
argc The argument count from the main function.
argv The argument vector from the main function.
Definition at line 59 of file main.cpp.
     : audio(),
       pfile(this, audio),
       pposition(this, Playd::POSITION_PERIOD),
       pstate(this),
       player(this, pfile, pposition, pstate),
       handler(player)
 {
     for (int i = 0; i < argc; i++) {
         this->argv.emplace_back(argv[i]);
     }
 }
Member Function Documentation
int Playd::GetDeviceID () private
Tries to get the output device ID from program arguments.
Returns
The device ID, INVALID_ID if invalid selection (or none).
Definition at line 39 of file main.cpp.
References argv, audio, INVALID_ID, and PaSoxAudioSystem::IsOutputDevice().
Referenced by Run().
 {
     // Did the user provide an ID at all?
     if (this->argv.size() < 2) return this->INVALID_ID;
     // Only accept valid numbers (stoi will throw for invalid ones).
     int id;
     try {
         id = std::stoi(this->argv.at(1));
     } catch (...) {
         // Only std::{invalid_argument,out_of_range} are thrown here.
         return this->INVALID_ID;
     }
     // Only allow valid, outputtable devices; reject input-only devices.
     if (!this->audio.IsOutputDevice(id)) return this->INVALID_ID;
     return id;
 }
void Playd::RespondRaw (const std::string & string) const override private virtual
Outputs a raw response string.
Parameters
string The raw, escaped response string.
Implements ResponseSink.
Definition at line 118 of file main.cpp.
References io.
 {
     if (this->io != nullptr) this->io->Broadcast(string);
 }
int Playd::Run ()
Runs playd.
Returns
The exit code, which may be returned by the program.
Definition at line 72 of file main.cpp.
References argv, audio, GetDeviceID(), PaSoxAudioSystem::GetDevicesInfo(), handler, INVALID_ID, io, Error::Message(), player, and PaSoxAudioSystem::SetDeviceID().
Referenced by main().
 {
     // Fill in some default arguments.
     // Note that we don't have a default device ID; if the user doesn't
     // supply an ID, we treat it as if they had supplied an invalid one.
     auto size = this->argv.size();
     std::string addr = size > 2 ? this->argv.at(2) : "0.0.0.0";
     std::string port = size > 3 ? this->argv.at(3) : "1350";
     // Now set up the device ID.
     // Do this now, so that an invalid ID is caught before we start trying
     // to acquire the network socket.
     int id = this->GetDeviceID();
     if (id == INVALID_ID) {
         // Show the user the valid device IDs they can use.
         auto device_list = this->audio.GetDevicesInfo();
         for (const auto &device : device_list) {
             std::cout << device.first << ": " << device.second
                       << std::endl;
         }
         return EXIT_FAILURE;
     }
     this->audio.SetDeviceID(id);
     // Now set up all the IO (network socket and event loop).
     try {
         this->io = decltype(this->io)(new IoCore(
                         this->player, this->handler, addr, port));
     } catch (NetError &e) {
         std::cerr << "Network error: " << e.Message() << std::endl;
         std::cerr << "Is " << addr << ":" << port << " available?"
                   << std::endl;
         return EXIT_FAILURE;
     }
     try {
         this->io->Run();
     } catch (Error &error) {
         std::cerr << "Unhandled exception in main loop: "
                   << error.Message() << std::endl;
         return EXIT_FAILURE;
     }
     return EXIT_SUCCESS;
 }
Member Data Documentation
const std::uint64_t Playd::POSITION_PERIOD = 500000 static private
The period between position announcements from the Player object.
This is given in microseconds, so eg. 500000 = 0.5sec = 2Hz.
Definition at line 52 of file main.hpp.
The documentation for this class was generated from the following files:
src/main.hpp
src/main.cpp