URY playd: ResponseSink Class Reference
ResponseSink Class Reference abstract
Abstract class for anything that can be sent a response.
#include <io_response.hpp>
Public Member Functions
void Respond (ResponseCode code, const std::string &message) const
Outputs a response with a single message argument.
void RespondArgs (ResponseCode code, const std::vector< std::string > &arguments) const
Outputs a response with multiple message arguments.
Protected Member Functions
virtual void RespondRaw (const std::string &string) const =0
Outputs a raw response string.
Static Private Member Functions
static std::string EscapeArgument (const std::string &argument)
Escapes a single response argument.
Detailed Description
Abstract class for anything that can be sent a response.
Usually the responses come from a ResponseSource, but anything may send a ResponseSink a response.
See also
ResponseSource
Definition at line 49 of file io_response.hpp.
Member Function Documentation
std::string ResponseSink::EscapeArgument (const std::string & argument) static private
Escapes a single response argument.
Parameters
argument The argument to escape.
Returns
The escaped argument.
Definition at line 45 of file io_response.cpp.
Referenced by RespondArgs().
 {
     bool escaping = false;
     std::string escaped;
     for (unsigned char c : argument) {
         bool is_escaper = c == '"' || c == '\'' || c == '\\';
         if (isspace(c) || is_escaper) escaping = true;
         // Since we use single-quote escaping, the only thing we need
         // to escape by itself is single quotes, which are replaced by
         // the sequence '\'' (break out of single quotes, escape a
         // single quote, then re-enter single quotes).
         escaped += (c == '\'') ? R"('\'')" : std::string(1, c);
     }
     if (escaping) return "'" + escaped + "'";
     return escaped;
 }
void ResponseSink::Respond (ResponseCode code, const std::string & message) const
Outputs a response with a single message argument.
Parameters
code The code of the response to emit.
message The unescaped response message.
See also
RespondArgs
Definition at line 29 of file io_response.cpp.
References RespondArgs().
Referenced by PlayerFile::Emit(), PlayerState::Emit(), PlayerPosition::Emit(), CommandResult::Emit(), and Player::WelcomeClient().
 {
     this->RespondArgs(code, std::vector<std::string>(1, message));
 }
void ResponseSink::RespondArgs (ResponseCode code, const std::vector< std::string > & arguments) const
Outputs a response with multiple message arguments.
Parameters
code The code of the response to emit.
arguments The vector of unescaped arguments to emit.
See also
Respond
Definition at line 34 of file io_response.cpp.
References EscapeArgument(), and RespondRaw().
Referenced by CommandResult::Emit(), Player::End(), Respond(), and Player::WelcomeClient().
 {
     std::ostringstream os;
     os << RESPONSES[static_cast<int>(code)];
     for (auto argument : arguments) {
         os << " " << this->EscapeArgument(argument);
     }
     this->RespondRaw(os.str());
 }
virtual void ResponseSink::RespondRaw (const std::string & string) const protected pure virtual
Outputs a raw response string.
Parameters
string The raw, escaped response string.
Implemented in IoCore, Connection, and ConnectionPool.
Referenced by RespondArgs().
The documentation for this class was generated from the following files:
src/io/io_response.hpp
src/io/io_response.cpp