URY playd: PlayerFile Class Reference
PlayerFile Class Reference
The subcomponent of a Player that stores the audio file.
#include <player_file.hpp>
Public Member Functions
PlayerFile (const ResponseSink *file_sink, const AudioSystem &audio_system)
Constructs a new PlayerFile.
void Eject ()
Ejects the current file.
void Load (const std::string &path)
Opens a file and stores it in this PlayerFile.
void Start () override
Starts playback of this Audio.
void Stop () override
Stops playback of this Audio.
void Emit (const ResponseSink &sink) const override
Emits a FILE response containing this Audio's path.
Audio::State Update () override
Performs an update cycle on this Audio.
std::uint64_t Position () const override
This Audio's current position.
void Seek (std::uint64_t position) override
Attempts to seek to the given position.
Public Member Functions inherited from ResponseSource
ResponseSource (const ResponseSink *push_sink)
Constructs a ResponseSource.
Private Attributes
std::unique_ptr< Audio > audio
The audio file.
const AudioSystem & audio_system
The audio system responsible for creating audio files.
Additional Inherited Members
Public Types inherited from Audio
enum State : uint8_t { State::NONE, State::STOPPED, State::PLAYING, State::AT_END }
Enumeration of possible states for this Audio.
Protected Member Functions inherited from ResponseSource
void Push () const
Calls an Emit on the registered ResponseSink.
Detailed Description
The subcomponent of a Player that stores the audio file.
This itself adheres to the Audio interface.
See also
Audio
Player
Definition at line 26 of file player_file.hpp.
Constructor & Destructor Documentation
PlayerFile::PlayerFile (const ResponseSink * file_sink, const AudioSystem & audio_system)
Constructs a new PlayerFile.
Parameters
file_sink The ResponseSink to which FILE responses are pushed.
audio_system The AudioSystem to use for audio loads.
Definition at line 18 of file player_file.cpp.
     : ResponseSource(file_sink), audio(nullptr), audio_system(audio_system)
 {
 }
Member Function Documentation
void PlayerFile::Eject ()
Ejects the current file.
See also
Load
Definition at line 24 of file player_file.cpp.
References audio.
Referenced by Player::Eject(), and Load().
 {
     // Don't bother actually ejecting if there isn't anything to eject.
     if (this->audio == nullptr) return;
     this->audio->Stop();
     this->audio = nullptr;
 }
void PlayerFile::Emit (const ResponseSink & sink) const override virtual
Emits a FILE response containing this Audio's path.
This is usually literally the absolute file-path, but depends on the implementation.
Parameters
sink The ResponseSink to which the response shall be sent.
Implements Audio.
Definition at line 56 of file player_file.cpp.
References audio.
Referenced by Player::WelcomeClient().
 {
     if (this->audio != nullptr) this->audio->Emit(sink);
 }
void PlayerFile::Load (const std::string & path)
Opens a file and stores it in this PlayerFile.
Parameters
path The absolute path to a track to load.
See also
Eject
Definition at line 33 of file player_file.cpp.
References audio, audio_system, Eject(), AudioSystem::Load(), and ResponseSource::Push().
Referenced by Player::Load().
 {
     // We can load over existing audio, but we need to eject it first.
     if (this->audio != nullptr) this->Eject();
     this->audio = decltype(this->audio)(this->audio_system.Load(path));
     // Let clients know the file has changed.
     this->Push();
 }
std::uint64_t PlayerFile::Position () const override virtual
This Audio's current position.
As this may be executing whilst the playing callback is running, do not expect it to be highly accurate.
Returns
The current position, in microseconds.
See also
Seek
Implements Audio.
Definition at line 67 of file player_file.cpp.
References audio.
Referenced by Player::SeekRaw(), and Player::Update().
 {
     assert(this->audio != nullptr);
     return this->audio->Position();
 }
void PlayerFile::Seek (std::uint64_t position) override virtual
Attempts to seek to the given position.
Parameters
position The position to seek to, in microseconds.
See also
Position
Implements Audio.
Definition at line 73 of file player_file.cpp.
References audio.
Referenced by Player::SeekRaw().
 {
     assert(this->audio != nullptr);
     this->audio->Seek(position);
 }
void PlayerFile::Start () override virtual
Starts playback of this Audio.
See also
Stop
Implements Audio.
Definition at line 44 of file player_file.cpp.
References audio.
Referenced by Player::Play().
 {
     assert(this->audio != nullptr);
     this->audio->Start();
 }
void PlayerFile::Stop () override virtual
Stops playback of this Audio.
See also
Start
Implements Audio.
Definition at line 50 of file player_file.cpp.
References audio.
Referenced by Player::Stop().
 {
     assert(this->audio != nullptr);
     this->audio->Stop();
 }
Audio::State PlayerFile::Update () override virtual
Performs an update cycle on this Audio.
Depending on the Audio implementation, this may do actions such as performing a decoding round, checking for end-of-file, transferring frames, and so on.
Returns
The state of the Audio after updating.
See also
State
Implements Audio.
Definition at line 61 of file player_file.cpp.
References audio, and Audio::NONE.
Referenced by Player::Update().
 {
     if (this->audio == nullptr) return Audio::State::NONE;
     return this->audio->Update();
 }
The documentation for this class was generated from the following files:
src/player/player_file.hpp
src/player/player_file.cpp