URY playd: PlayerPosition Class Reference
PlayerPosition Class Reference
Tracker and broadcaster for the Player's current position in a song.
#include <player_position.hpp>
Public Member Functions
PlayerPosition ()
Constructs a PlayerPosition.
void SetResponsePeriod (TimeParser::MicrosecondPosition period)
Sets the period between position signals.
void Update (TimeParser::MicrosecondPosition position)
Updates the position tracker with the new position.
void Reset ()
Resets the position tracker's position data.
void Emit (ResponseSink &sink) const override
Emits the current position to a ResponseSink.
Public Member Functions inherited from ResponseSource
void SetResponseSink (ResponseSink &sink)
Registers a ResponseSink with this ResponseSource.
Private Member Functions
bool IsReadyToSend () const
Figures out whether it's time to send a position signal.
void Send ()
Sends a position signal to the outside environment, if ready.
Private Attributes
TimeParser::MicrosecondPosition period
The period between each push of the position to the response sink.
TimeParser::MicrosecondPosition current
The current position of the player.
TimeParser::MicrosecondPosition last
The position of the player at the last push.
bool has_reset
Whether the position was reset since the last push.
Additional Inherited Members
Protected Member Functions inherited from ResponseSource
void Push () const
Calls an Emit on the registered ResponseSink.
Detailed Description
Tracker and broadcaster for the Player's current position in a song.
See also
Player
PlayerState
Definition at line 24 of file player_position.hpp.
Member Function Documentation
void PlayerPosition::Emit (ResponseSink & sink) const override virtual
Emits the current position to a ResponseSink.
Parameters
sink The ResponseSink to which a TIME response shall be sent.
Implements ResponseSource.
Definition at line 66 of file player_position.cpp.
References current, ResponseSink::Respond(), and TIME.
Referenced by Player::WelcomeClient().
 {
     target.Respond(ResponseCode::TIME, std::to_string(this->current));
 }
bool PlayerPosition::IsReadyToSend () const private
Figures out whether it's time to send a position signal.
Returns
True if enough time has elapsed for a signal to be sent; false otherwise.
Definition at line 71 of file player_position.cpp.
References current, has_reset, last, and period.
Referenced by Update().
 {
     return this->has_reset || (this->last + this->period <= this->current);
 }
void PlayerPosition::Reset ()
Resets the position tracker's position data.
This does not remove any registered push response sink. Call this whenever the song changes, or before a skip.
See also
Update
Definition at line 59 of file player_position.cpp.
References current, has_reset, and last.
Referenced by PlayerPosition(), and Player::ResetPosition().
 {
     this->current = TimeParser::MicrosecondPosition(0);
     this->last = TimeParser::MicrosecondPosition(0);
     this->has_reset = true;
 }
void PlayerPosition::Send () private
Sends a position signal to the outside environment, if ready.
This only sends a signal if the requested amount of time has passed since the last one.
void PlayerPosition::SetResponsePeriod (TimeParser::MicrosecondPosition period)
Sets the period between position signals.
This is shared across all listeners.
Parameters
period The period to wait between responses.
See also
SetResponseSink
Definition at line 76 of file player_position.cpp.
References period.
Referenced by Player::SetPositionResponsePeriod().
 {
     this->period = period;
 }
void PlayerPosition::Update (TimeParser::MicrosecondPosition position)
Updates the position tracker with the new position.
This pushes the position to the registered response sink, if necessary.
Parameters
position The new position, in PositionUnit units.
See also
Reset
Definition at line 48 of file player_position.cpp.
References current, has_reset, IsReadyToSend(), last, and ResponseSource::Push().
Referenced by Player::UpdatePosition().
 {
     this->current = position;
     if (this->IsReadyToSend()) {
         this->Push();
         this->last = this->current;
         this->has_reset = 0;
     }
 }
Member Data Documentation
bool PlayerPosition::has_reset private
Whether the position was reset since the last push.
This is also set high if the position has never been emitted.
Definition at line 39 of file player_position.hpp.
Referenced by IsReadyToSend(), Reset(), and Update().
The documentation for this class was generated from the following files:
src/player/player_position.hpp
src/player/player_position.cpp