URY playd: ResponseSource Class Reference
ResponseSource Class Reference abstract
Abstract helper class for sources of responses.
#include <io_response.hpp>
Public Member Functions
ResponseSource (const ResponseSink *push_sink)
Constructs a ResponseSource.
virtual void Emit (const ResponseSink &sink) const =0
Emits a response to a given ResponseSink.
Protected Member Functions
void Push () const
Calls an Emit on the registered ResponseSink.
Private Attributes
const ResponseSink * push_sink
A ResponseSink to which 'push' responses are emitted.
Detailed Description
Abstract helper class for sources of responses.
A ResponseSource can both 'push' responses to a registered ResponseSink and be 'polled' from outside to dump its current response to an external ResponseSink.
For example, PlayerPosition 'pushes' its position every few milliseconds to the outside world, to keep the client aware of the time, but is also 'polled' on a new client connection so that the client immediately gets the current position on connect.
See also
ResponseSink
Definition at line 105 of file io_response.hpp.
Constructor & Destructor Documentation
ResponseSource::ResponseSource (const ResponseSink * push_sink)
Constructs a ResponseSource.
Parameters
push_sink A pointer to the ResponseSink to which Push() notifications shall be sent. May be nullptr, in which case said notifications are discarded.
Definition at line 74 of file io_response.cpp.
     : push_sink(push_sink)
 {
 }
Member Function Documentation
virtual void ResponseSource::Emit (const ResponseSink & sink) const pure virtual
Emits a response to a given ResponseSink.
Parameters
sink The ResponseSink to which this ResponseSource's current response should be emitted.
Implemented in PlayerPosition, PlayerState, and PlayerFile.
Referenced by Push().
void ResponseSource::Push () const protected
Calls an Emit on the registered ResponseSink.
If there is no registered ResponseSink, the response is dropped.
Definition at line 79 of file io_response.cpp.
References Emit(), and push_sink.
Referenced by PlayerFile::Load(), PlayerState::Set(), and PlayerPosition::Update().
 {
     // Having no push_sink is entirely normal, and implies that the
     // ResponseSource's responses are to be ignored.
     if (this->push_sink != nullptr) this->Emit(*this->push_sink);
 }
Member Data Documentation
const ResponseSink* ResponseSource::push_sink private
A ResponseSink to which 'push' responses are emitted.
If the ResponseSink is not present, responses are not emitted.
Definition at line 135 of file io_response.hpp.
Referenced by Push().
The documentation for this class was generated from the following files:
src/io/io_response.hpp
src/io/io_response.cpp