URY playd: TcpResponseSink Class Reference
TcpResponseSink Class Reference
A TCP connection from a client.
#include <io_reactor.hpp>
Public Member Functions
TcpResponseSink (IoReactor &parent, uv_tcp_t *tcp, CommandHandler &handler)
Constructs a TcpResponseSink.
void RespondRaw (const std::string &response) const override
Outputs a raw response string.
void Read (uv_stream_t *stream, ssize_t nread, const uv_buf_t *buf)
Processes a data read on this connection.
void Close ()
Closes this connection.
Public Member Functions inherited from ResponseSink
void Respond (ResponseCode code, const std::string &message) const
Outputs a response.
void RespondWithError (const Error &error) const
Emits an error as a response.
Private Attributes
IoReactor & parent
The parent IoReactor on which this connection is running.
uv_tcp_t * tcp
The libuv handle for the TCP connection.
Tokeniser tokeniser
The Tokeniser to which data read on this connection should be sent.
Additional Inherited Members
Public Types inherited from ResponseSink
using Callback = std::function< void(ResponseSink &)>
A type for callbacks taking a ResponseSink.
Detailed Description
A TCP connection from a client.
Todo:
Rename to Connection?
Definition at line 126 of file io_reactor.hpp.
Constructor & Destructor Documentation
TcpResponseSink::TcpResponseSink (IoReactor & parent, uv_tcp_t * tcp, CommandHandler & handler)
Constructs a TcpResponseSink.
Parameters
parent The IoReactor that is the parent of this connection.
tcp The underlying libuv TCP stream.
handler The handler to which read commands should be sent.
Definition at line 192 of file io_reactor.cpp.
     : parent(parent), tcp(tcp), tokeniser(handler, *this)
 {
 }
Member Function Documentation
void TcpResponseSink::Close ()
Closes this connection.
Todo:
Roll into the destructor/use RAII?
Definition at line 230 of file io_reactor.cpp.
References parent, and IoReactor::RemoveConnection().
Referenced by UvCloseCallback().
 {
     this->parent.RemoveConnection(*this);
 }
void TcpResponseSink::Read (uv_stream_t * stream, ssize_t nread, const uv_buf_t * buf)
Processes a data read on this connection.
Parameters
stream The libuv TCP/IP stream providing the data.
nread The number of bytes read.
buf The buffer containing the read data.
Definition at line 213 of file io_reactor.cpp.
References Tokeniser::Feed(), tokeniser, and UvCloseCallback().
Referenced by UvReadCallback().
 {
     if (nread < 0) {
         if (nread == UV_EOF) {
             uv_close((uv_handle_t *)stream, UvCloseCallback);
         }
         return;
     }
     if (buf->base != nullptr) {
         this->tokeniser.Feed(buf->base, nread);
         delete[] buf->base;
     }
 }
void TcpResponseSink::RespondRaw (const std::string & string) const override virtual
Outputs a raw response string.
Parameters
string The response string, of the form "CODE message".
Implements ResponseSink.
Definition at line 198 of file io_reactor.cpp.
References WriteReq::buf, tcp, and UvRespondCallback().
 {
     Debug() << "Sending command:" << string << std::endl;
     unsigned int l = string.length();
     const char *s = string.c_str();
     WriteReq *req = new WriteReq;
     req->buf = uv_buf_init(new char[l + 1], l + 1);
     memcpy(req->buf.base, s, l);
     req->buf.base[l] = '\n';
     uv_write((uv_write_t *)req, (uv_stream_t *)tcp, &req->buf, 1,
              UvRespondCallback);
 }
The documentation for this class was generated from the following files:
src/io/io_reactor.hpp
src/io/io_reactor.cpp