URY playd: TimeParser Class Reference
TimeParser Class Reference
A class for parsing time strings consisting of an integer and unit into a flat integer representing the number of OutUnit units that time string represents.
#include <time_parser.hpp>
Public Types
typedef std::uint64_t MicrosecondPosition
Type for microsecond positions emitted by this TimeParser.
Static Public Member Functions
static MicrosecondPosition Parse (const std::string &time_str)
Parses a time.
Private Types
enum Multiplier : MicrosecondPosition {
Multiplier::MICROSECONDS = 1, Multiplier::MILLISECONDS = 1000, Multiplier::SECONDS = 1000000, Multiplier::MINUTES = 60000000,
Multiplier::HOURS = 3600000000
}
Static Private Member Functions
static Multiplier UnitMultiplier (const std::string &unit)
Find the unit multiplier for a given unit suffix.
static std::pair< std::string,
MicrosecondPosition > Split (const std::string &time_str)
Splits a time string into a pair of unit and amount.
Detailed Description
A class for parsing time strings consisting of an integer and unit into a flat integer representing the number of OutUnit units that time string represents.
Definition at line 20 of file time_parser.hpp.
Member Enumeration Documentation
enum TimeParser::Multiplier : MicrosecondPosition strong private
Enumerator
MICROSECONDS
Microseconds in one microsecond.
MILLISECONDS
Microseconds in one millisecond.
SECONDS
Microseconds in one second.
MINUTES
Microseconds in one minute.
HOURS
Microseconds in one hour.
Definition at line 34 of file time_parser.hpp.
                           : MicrosecondPosition {
         MICROSECONDS = 1,
         MILLISECONDS = 1000,
         SECONDS = 1000000,
         MINUTES = 60000000,
         HOURS = 3600000000
     };
Member Function Documentation
TimeParser::MicrosecondPosition TimeParser::Parse (const std::string & time_str) static
Parses a time.
Parameters
time_str The time string.
Returns
The parsed time.
Definition at line 18 of file time_parser.cpp.
References Split(), and UnitMultiplier().
Referenced by Player::Seek().
 {
     auto seek = TimeParser::Split(time_str);
     std::string unit = seek.first;
     MicrosecondPosition num_units = seek.second;
     return static_cast<MicrosecondPosition>(
                            TimeParser::UnitMultiplier(unit)) *
            num_units;
 }
std::pair< std::string, TimeParser::MicrosecondPosition > TimeParser::Split (const std::string & time_str) static private
Splits a time string into a pair of unit and amount.
Parameters
time_str The time string.
Returns
A pair of unit string and time amount, as an integer in terms of the named unit.
Definition at line 46 of file time_parser.cpp.
References MSG_SEEK_FAIL.
Referenced by Parse().
 {
     std::istringstream is(time_str);
     MicrosecondPosition raw_time;
     std::string rest;
     is >> raw_time;
     // Make sure we actually get a time of some form.
     if (is.fail()) throw SeekError(MSG_SEEK_FAIL);
     is >> rest;
     return std::make_pair(rest, raw_time);
 }
TimeParser::Multiplier TimeParser::UnitMultiplier (const std::string & unit) static private
Find the unit multiplier for a given unit suffix.
The unit multiplier is the multiplier that converts from a time in unit units to a time in microseconds.
Parameters
unit The unit suffix.
Returns
The unit multiplier.
Exceptions
std::out_of_range if the unit is not recognised.
Definition at line 30 of file time_parser.cpp.
References HOURS, MICROSECONDS, MILLISECONDS, MINUTES, and SECONDS.
Referenced by Parse().
 {
     // Default to microseconds if no unit is given.
     if (unit.empty()) return Multiplier::MICROSECONDS;
     if (unit == "us") return Multiplier::MICROSECONDS;
     if (unit == "ms") return Multiplier::MILLISECONDS;
     if (unit == "s") return Multiplier::SECONDS;
     if (unit == "m") return Multiplier::MINUTES;
     if (unit == "h") return Multiplier::HOURS;
     throw std::out_of_range(unit);
 }
The documentation for this class was generated from the following files:
src/time_parser.hpp
src/time_parser.cpp