URY playd: CommandResult Class Reference
CommandResult Class Reference
A result from a command.
#include <cmd_result.hpp>
Public Types
enum Type : std::uint8_t { Type::SUCCESS, Type::INVALID, Type::FAILURE }
Enumeration of possible types of CommandResult.
Public Member Functions
CommandResult (Type type, const std::string &msg)
Constructs a CommandResult.
bool IsSuccess () const
Determines whether this CommandResult was successful.
void Emit (const ResponseSink &sink, const std::vector< std::string > &cmd) const
Sends a response to a ResponseSink about this CommandResult.
Static Public Member Functions
static CommandResult Success ()
Shortcut for constructing a successful CommandResult.
static CommandResult Invalid (const std::string &msg)
Shortcut for constructing an invalid-response CommandResult.
static CommandResult Failure (const std::string &msg)
Shortcut for constructing a failed CommandResult.
Private Attributes
Type type
The command result's type.
std::string msg
The command result's message.
Static Private Attributes
static const ResponseCode TYPE_CODES []
Map of types to their response codes.
Detailed Description
A result from a command.
Commands may either succeed (with no failure message), or fail (with a failure message). The success (or not) of a command may be checked with CommandResult::IsSuccess.
Definition at line 26 of file cmd_result.hpp.
Member Enumeration Documentation
enum CommandResult::Type : std::uint8_t strong
Enumeration of possible types of CommandResult.
Note
If changing this, change CommandResult::TYPE_CODES too.
See also
CommandResult::TYPE_CODES
Todo:
Investigate whether polymorphism would be better?
Enumerator
SUCCESS
The command was successful.
INVALID
The command request was not well-formed.
FAILURE
The command request was valid, but failed.
Definition at line 35 of file cmd_result.hpp.
                     : std::uint8_t {
         SUCCESS,
         INVALID,
         FAILURE
     };
Constructor & Destructor Documentation
CommandResult::CommandResult (CommandResult::Type type, const std::string & msg)
Constructs a CommandResult.
Parameters
type The type of command result.
msg A message providing more information about the result. This will typically only be used for failures. The message will be copied into the CommandResult.
Definition at line 37 of file cmd_result.cpp.
Referenced by Failure(), Invalid(), and Success().
     : type(type), msg(msg)
 {
 }
Member Function Documentation
void CommandResult::Emit (const ResponseSink & sink, const std::vector< std::string > & cmd) const
Sends a response to a ResponseSink about this CommandResult.
If the CommandResult was a success, then the response is 'OK cmd', where 'cmd' is the parameter named as such. Otherwise, the response is 'X msg', where 'msg' is the result message and 'X' is whichever response code is most appropriate for the failure.
Parameters
sink The ResponseSink to which the response will be sent.
cmd The original command that created this CommandResult.
Definition at line 47 of file cmd_result.cpp.
References msg, ResponseSink::RespondArgs(), SUCCESS, type, and TYPE_CODES.
Referenced by Connection::HandleCommand().
 {
     std::vector<std::string> args(cmd);
     // Only display a message if the result wasn't a successful one.
     // The message goes at the front, as then clients always know it's the
     // first argument.
     if (this->type != Type::SUCCESS) args.insert(args.begin(), this->msg);
     auto code = CommandResult::TYPE_CODES[static_cast<uint8_t>(this->type)];
     sink.RespondArgs(code, args);
 }
CommandResult CommandResult::Failure (const std::string & msg) static
Shortcut for constructing a failed CommandResult.
Parameters
msg The failure message. See CommandResult().
Returns
A CommandResult denoting failure.
Definition at line 32 of file cmd_result.cpp.
References CommandResult(), and FAILURE.
Referenced by Player::Load().
 {
     return CommandResult(Type::FAILURE, msg);
 }
CommandResult CommandResult::Invalid (const std::string & msg) static
Shortcut for constructing an invalid-response CommandResult.
Parameters
msg The failure message. See CommandResult().
Returns
A CommandResult denoting an invalid response.
Definition at line 27 of file cmd_result.cpp.
References CommandResult(), and INVALID.
Referenced by Player::Eject(), CommandHandler::Handle(), Player::Load(), Player::Play(), CommandHandler::RunNullary(), CommandHandler::RunUnary(), Player::Seek(), and Player::Stop().
 {
     return CommandResult(Type::INVALID, msg);
 }
bool CommandResult::IsSuccess () const
Determines whether this CommandResult was successful.
Returns
True if the result was a success; false otherwise.
Definition at line 42 of file cmd_result.cpp.
References SUCCESS, and type.
 {
     return this->type == Type::SUCCESS;
 }
CommandResult CommandResult::Success () static
Shortcut for constructing a successful CommandResult.
Returns
A CommandResult denoting success.
Definition at line 22 of file cmd_result.cpp.
References CommandResult(), and SUCCESS.
Referenced by Player::Eject(), Player::Load(), Player::Play(), Player::Quit(), Player::Seek(), and Player::Stop().
 {
     return CommandResult(Type::SUCCESS, "success");
 }
Member Data Documentation
const ResponseCode CommandResult::TYPE_CODES static private
Initial value:
= {
    ResponseCode::OK,
    ResponseCode::WHAT,
    ResponseCode::FAIL,
}
Map of types to their response codes.
See also
ResponseCode
Type
Definition at line 99 of file cmd_result.hpp.
Referenced by Emit().
The documentation for this class was generated from the following files:
src/cmd_result.hpp
src/cmd_result.cpp