URY playd: AudioSink Class Reference
AudioSink Class Reference
An output stream for an Audio file.
#include <audio_sink.hpp>
Public Types
typedef std::uint64_t SamplePosition
Type of positions measured in samples.
typedef
AudioSource::DecodeVector::iterator TransferIterator
Type of iterators used in the Transfer() method.
Public Member Functions
AudioSink (const AudioSource &source, const AudioSinkConfigurator &conf)
Constructs an AudioSink.
void Start ()
Starts the audio stream.
void Stop ()
Stops the audio stream.
bool IsStopped ()
Checks to see if audio playback has stopped.
SamplePosition Position ()
Gets the current played position in the song, in samples.
void SetPosition (SamplePosition samples)
Sets the current played position, given a position in samples.
bool InputReady ()
Gets whether this AudioSink is expecting input.
void SetInputReady (bool ready)
Set whether this AudioSink can expect input.
void Transfer (TransferIterator &start, const TransferIterator &end)
Transfers a range of sample bytes into the AudioSink.
Private Member Functions
int paCallbackFun (const void *inputBuffer, void *outputBuffer, unsigned long numFrames, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags) override
The callback proper.
PlayCallbackStepResult PlayCallbackStep (char *out, unsigned long frames_per_buf, PlayCallbackStepResult in)
Performs one step in the callback.
PlayCallbackStepResult PlayCallbackSuccess (char *out, unsigned long avail, unsigned long frames_per_buf, PlayCallbackStepResult in)
Performs a successful play callback step.
PlayCallbackStepResult PlayCallbackFailure (char *out, unsigned long avail, unsigned long frames_per_buf, PlayCallbackStepResult in)
Performs error cleanup for a failed play callback step.
unsigned long ReadSamplesToOutput (char *&output, unsigned long output_capacity, unsigned long buffered_count)
Reads from the ringbuffer to output, updating the used samples count.
Private Attributes
AudioSource::SampleByteCount bytes_per_sample
Number of bytes in one sample.
RingBuffer< char, unsigned long > ring_buf
The ring buffer used to transfer samples to the playing callback.
std::unique_ptr
< portaudio::Stream > stream
The PortAudio stream to which this AudioSink outputs.
std::uint64_t position_sample_count
The current position, in samples.
bool just_started
Whether the current run of the audio playback stream has not yet successfully read its first set of samples from the buffer.
bool input_ready
Whether there is input ready for this sink.
Static Private Attributes
static const size_t RINGBUF_POWER = 16
n, where 2^n is the capacity of the Audio ring buffer.
Detailed Description
An output stream for an Audio file.
An AudioSink consists of a PortAudio output stream and a buffer that stores decoded samples from the Audio object. While active, the AudioSink periodically transfers samples from its buffer to PortAudio in a separate thread.
Definition at line 54 of file audio_sink.hpp.
Constructor & Destructor Documentation
AudioSink::AudioSink (const AudioSource & source, const AudioSinkConfigurator & conf)
Constructs an AudioSink.
Parameters
source The source from which this sink will receive audio.
conf The configurator to use to create streams for this sink.
Definition at line 27 of file audio_sink.cpp.
References AudioSinkConfigurator::Configure(), and stream.
     : bytes_per_sample(source.BytesPerSample()),
       ring_buf(RINGBUF_POWER, source.BytesPerSample()),
       position_sample_count(0),
       just_started(false),
       input_ready(false)
 {
     this->stream = decltype(this->stream)(conf.Configure(source, *this));
 }
Member Function Documentation
bool AudioSink::InputReady ()
Gets whether this AudioSink is expecting input.
Returns
Whether the input-ready flag has been set.
See also
SetInputReady
Definition at line 56 of file audio_sink.cpp.
References input_ready.
Referenced by PlayCallbackFailure().
 {
     return this->input_ready;
 }
bool AudioSink::IsStopped ()
Checks to see if audio playback has stopped.
Returns
True if the audio stream is inactive; false otherwise.
See also
Start
Stop
Definition at line 51 of file audio_sink.cpp.
References stream.
 {
     return !this->stream->isActive();
 }
int AudioSink::paCallbackFun (const void * inputBuffer, void * outputBuffer, unsigned long numFrames, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags) override private
The callback proper.
This is executed in a separate thread by PortAudio once a stream is playing with the callback registered to it.
Parameters
inputBuffer The buffer containing input data; ignored.
outputBuffer The output buffer to which our samples should be written.
numFrames The number of samples PortAudio wants to read from outputBuffer.
timeInfo The time information from PortAudio; ignored.
statusFlags The PortAudio status flags; ignored.
Returns
The number of samples written to the output buffer.
Definition at line 108 of file audio_sink.cpp.
References PlayCallbackStep().
 {
     char *cout = static_cast<char *>(out);
     std::pair<PaStreamCallbackResult, unsigned long> result =
                     std::make_pair(paContinue, 0);
     while (result.first == paContinue && result.second < frames_per_buf) {
         result = PlayCallbackStep(cout, frames_per_buf, result);
     }
     return static_cast<int>(result.first);
 }
PlayCallbackStepResult AudioSink::PlayCallbackFailure (char * out, unsigned long avail, unsigned long frames_per_buf, PlayCallbackStepResult in) private
Performs error cleanup for a failed play callback step.
This ensures that the output buffer is filled with silence and the correct error code is returned.
Parameters
out The output buffer to which our samples should be written.
avail The number of samples available in the ring buffer.
frames_per_buf The number of samples PortAudio wants to read out.
in The result from the previous PlayCallbackStep.
Returns
A PlayCallbackStepResult containing the status code and number of samples written as of the end of this step.
Definition at line 154 of file audio_sink.cpp.
References bytes_per_sample, and InputReady().
Referenced by PlayCallbackStep().
 {
     decltype(in) result;
     if (this->InputReady()) {
         // There's been some sort of genuine issue.
         // Make up some silence to plug the gap.
         Debug() << "Buffer underflow" << std::endl;
         memset(out, 0, this->bytes_per_sample * frames_per_buf);
         result = std::make_pair(paContinue, frames_per_buf);
     } else {
         // End of input is ok, it means the stream can finish.
         result = std::make_pair(paComplete, in.second);
     }
     return result;
 }
PlayCallbackStepResult AudioSink::PlayCallbackStep (char * out, unsigned long frames_per_buf, PlayCallbackStepResult in) private
Performs one step in the callback.
Parameters
out The output buffer to which our samples should be written.
frames_per_buf The number of samples PortAudio wants to read out.
in The result from the previous PlayCallbackStep.
Returns
A PlayCallbackStepResult containing the status code and number of samples written as of the end of this step.
Definition at line 124 of file audio_sink.cpp.
References just_started, PlayCallbackFailure(), PlayCallbackSuccess(), RingBuffer< RepT, SampleCountT >::ReadCapacity(), and ring_buf.
Referenced by paCallbackFun().
 {
     unsigned long avail = this->ring_buf.ReadCapacity();
     bool empty = avail == 0;
     /* If we've just started this stream, we don't want to hand PortAudio
        an incomplete framewe'd rather wait until we have enough in the
        ring buffer before starting to play out. */
     bool wait = this->just_started && (avail < frames_per_buf);
     bool failed = wait || empty;
     auto fn = failed ? &AudioSink::PlayCallbackFailure
                      : &AudioSink::PlayCallbackSuccess;
     return (this->*fn)(out, avail, frames_per_buf, in);
 }
PlayCallbackStepResult AudioSink::PlayCallbackSuccess (char * out, unsigned long avail, unsigned long frames_per_buf, PlayCallbackStepResult in) private
Performs a successful play callback step.
This ensures that the appropriate number of samples are read into PortAudio's buffer.
Parameters
out The output buffer to which our samples should be written.
avail The number of samples available in the ring buffer.
frames_per_buf The number of samples PortAudio wants to read out.
in The result from the previous PlayCallbackStep.
Returns
A PlayCallbackStepResult containing the status code and number of samples written as of the end of this step.
Definition at line 142 of file audio_sink.cpp.
References just_started, and ReadSamplesToOutput().
Referenced by PlayCallbackStep().
 {
     this->just_started = false;
     auto samples_pa_wants = frames_per_buf - in.second;
     auto samples_read = ReadSamplesToOutput(out, avail, samples_pa_wants);
     return std::make_pair(paContinue, in.second + samples_read);
 }
AudioSink::SamplePosition AudioSink::Position ()
Gets the current played position in the song, in samples.
As this may be executing whilst the playing callback is running, do not expect it to be highly accurate.
Returns
The current position, as a count of elapsed samples.
See also
SamplePosition
Definition at line 66 of file audio_sink.cpp.
References position_sample_count.
 {
     return this->position_sample_count;
 }
unsigned long AudioSink::ReadSamplesToOutput (char *& output, unsigned long output_capacity, unsigned long buffered_count) private
Reads from the ringbuffer to output, updating the used samples count.
Parameters
output A reference to the output buffer's current pointer.
output_capacity The capacity of the output buffer, in samples.
buffered_count The number of samples available in the ring buffer.
Returns
The number of samples successfully written to the output buffer.
Definition at line 174 of file audio_sink.cpp.
References position_sample_count, RingBuffer< RepT, SampleCountT >::Read(), and ring_buf.
Referenced by PlayCallbackSuccess().
 {
     // Transfer the maximum that we can offer to PortAudio without
     // overshooting
     // its sample request limit.
     long transfer_sample_count = static_cast<long>(
                     std::min({ output_capacity, buffered_count,
                            static_cast<unsigned long>(LONG_MAX) }));
     output += this->ring_buf.Read(output, transfer_sample_count);
     // Update the position count so it reflects the last position that was
     // sent
     // for playback (*not* the last position decoded).
     this->position_sample_count += transfer_sample_count;
     return transfer_sample_count;
 }
void AudioSink::SetInputReady (bool ready)
Set whether this AudioSink can expect input.
Parameters
ready True if there is input ready; false otherwise.
See also
InputReady
Definition at line 61 of file audio_sink.cpp.
References input_ready.
 {
     this->input_ready = ready;
 }
void AudioSink::SetPosition (AudioSink::SamplePosition samples)
Sets the current played position, given a position in samples.
This flushes out the AudioSink ready to receive sample data from the new position.
Parameters
samples The new position, as a count of elapsed samples.
See also
Position
Definition at line 71 of file audio_sink.cpp.
References RingBuffer< RepT, SampleCountT >::Flush(), position_sample_count, and ring_buf.
 {
     this->position_sample_count = samples;
     this->ring_buf.Flush();
 }
void AudioSink::Start ()
Starts the audio stream.
See also
Stop
IsHalted
Definition at line 38 of file audio_sink.cpp.
References just_started, and stream.
 {
     this->just_started = true;
     this->stream->start();
 }
void AudioSink::Stop ()
Stops the audio stream.
See also
Start
IsHalted
Definition at line 44 of file audio_sink.cpp.
References stream.
 {
     if (!this->stream->isStopped()) {
         this->stream->abort();
     }
 }
void AudioSink::Transfer (AudioSink::TransferIterator & start, const TransferIterator & end)
Transfers a range of sample bytes into the AudioSink.
The range may be empty, but must be valid.
Precondition: start <= end, start and end point to a valid contiguous block of sample bytes.
Postcondition: start <= end, old(start) <= start, *start and end point to a valid contiguous block of sample bytes.
Parameters
start An iterator denoting the start of the range. This iterator will be advanced by the number of bytes accepted.
end An iterator denoting the end of the range.
Definition at line 77 of file audio_sink.cpp.
References bytes_per_sample, ring_buf, RingBuffer< RepT, SampleCountT >::Write(), and RingBuffer< RepT, SampleCountT >::WriteCapacity().
 {
     assert(start < end);
     // No point transferring 0 bytes.
     if (start == end) return;
     unsigned long bytes = std::distance(start, end);
     // There should be a whole number of samples being transferred.
     assert(bytes % bytes_per_sample == 0);
     assert(0 < bytes);
     auto samples = bytes / this->bytes_per_sample;
     // Only transfer as many samples as the ring buffer can take.
     // Don't bother trying to write 0 samples!
     auto count = std::min(samples, this->ring_buf.WriteCapacity());
     assert(0 < count);
     if (count == 0) return;
     auto start_ptr = reinterpret_cast<char *>(&*start);
     unsigned long written_count = this->ring_buf.Write(start_ptr, count);
     // Since we never write more than the ring buffer can take, the written
     // count should equal the requested written count.
     assert(written_count == count);
     start += (written_count * this->bytes_per_sample);
     assert(start <= end);
 }
Member Data Documentation
bool AudioSink::just_started private
Whether the current run of the audio playback stream has not yet successfully read its first set of samples from the buffer.
Definition at line 158 of file audio_sink.hpp.
Referenced by PlayCallbackStep(), PlayCallbackSuccess(), and Start().
const size_t AudioSink::RINGBUF_POWER = 16 static private
n, where 2^n is the capacity of the Audio ring buffer.
See also
RINGBUF_SIZE
Definition at line 142 of file audio_sink.hpp.
The documentation for this class was generated from the following files:
src/audio/audio_sink.hpp
src/audio/audio_sink.cpp