.\"--
.\" This file is part of playd.
.\" playd is licensed under the MIT licence: see LICENSE.txt.
.\"--
.\"
.\" playd man page.
.\" This man page uses the 'mdoc' macro set; see `man mdoc` for details.
.\"
.Dd December 5, 2014
.Dt PLAYD 1
.Os
.\"
.\"======
.Sh NAME
.\"======
.Nm playd
.Nd basic TCP/IP-driven audio player
.\"
.\"==========
.Sh SYNOPSIS
.\"==========
.Nm
.Op Ar device-id
.Op Ar address
.Op Ar port
.\"
.\"=============
.Sh DESCRIPTION
.\"=============
.Nm
is a simple audio player,
intended to be driven by other software via a line-based TCP protocol.
Its feature set is described in
.Sx COMMANDS .
.Pp
.Nm
has a simple feature list: it can
load one audio file (given its path),
play that file,
pause playback of that file,
seek and eject that file,
and periodically emit the current position in that file.
.\"------------
.Ss Invocation
.\"------------
If no arguments are given,
.Nm
lists all possible valid values for the
.Ar device
argument.
Otherwise, it is launched as a daemon, with the arguments meaning:
.Bl -tag -width "address" -offset indent
.\"-
.It Ar device
The ID of the device onto which
.Nm
will output audio.  The
.Ar device
.Em must
be on the list given when
.Nm
is executed with zero arguments.
.\"-
.It Ar address
The IP address to which
.Nm
will bind when listening for client connections;
the default is 127.0.0.1 (only local connections).
To accept all connections, use 0.0.0.0.
.\"-
.It Ar port
The TCP port on which
.Nm
will listen for client connections; the default is 1350.
.El
.\"----------
.Ss Protocol
.\"----------
.Nm
speaks a simple, textual protocol inspired by the POSIX shell:
.Bl -dash -offset indent -compact
.It
Requests and responses consist of one or more whitespace-delimited
.Em words ,
followed by a line-feed.
.It
The first word, the
.Em command word ,
denotes the specific request or response.
A command word in
.Em lowercase
denotes a request; in
.Em CAPITALS ,
a response:
.Nm
is case-sensitive.
.It
Words may contain backslashes, which
.Em escape
the next character, reproducing it verbatim.
This can be used to permit whitespace, which would otherwise end the word.
.It
In addition, words may be
.Em quoted
in either
.Em double quotes ,
in which backslash escaping is respected, or
.Em single quotes ,
in which it is ignored.
.El
.\"-----------------------------
.Ss Controlling from a terminal
.\"-----------------------------
Since
.Nm
only speaks TCP/IP (by design),
it can be hard to speak with it from a terminal on the local machine.
Programs such as
.Xr nc 1
may bridge this gap in functionality.
.\"
.\"==========
.Sh COMMANDS
.\"==========
The sets of valid requests to, and responses from, a
.Nm
session are:
.\"
.\"----------
.Ss Requests
.\"----------
.Bl -tag -width "load path" -offset indent
.It eject
Unloads the current file, stopping any playback.
.It load Ar path
Loads the file at
.Ar path ,
which must be absolute.
.It play
Starts, or resumes, playback of the current file.
.It seek Ar pos
Seeks to
.Ar pos
microseconds past the start of the file.
Seeking past a file's end is equivalent to seeking to the end directly.
.It stop
Stops playback of the current file, keeping the current position.
.It quit
Makes
.Nm
quit.
.El
.\"
.\"-----------
.Ss Responses
.\"-----------
.Bl -tag -width "FILE path " -offset indent
.\"
.It END
The loaded file has reached its physical end.
.\"
.It FAIL Ar reason Ar command...
.Nm
failed to execute
.Ar command .
A human-readable
.Ar reason
is provided.
.\"
.It FEATURES Ar feature1 Op Ar feature2...
The set of BAPS3 feature flags
.Nm
implements.  This identifies the features
.Nm
provides to external clients.
.\"
.It FILE Ar path
The loaded file has changed to the file at
.Ar path .
.\"
.It OHAI Ar ident
Sent upon connection;
.Ar ident
identifies the playd server and version number.
.\"
.It OK Ar command...
.Nm
just finished processing
.Ar command .
.\"
.It STATE Ar state
The playback state has changed to
.Ar state .
This may be one of the following:
.Bl -tag -width "Quitting" -offset indent
.It Ejected
No file is loaded.
.It Playing
A file is loaded and playing.
.It Quitting
.Nm
is about to shut down.
.It Stopped
A file is loaded, but is not playing.
.El
.\"
.It TIME Ar pos
Periodic announcement of the current file position in microseconds,
.Ar pos .
.\"
.It WHAT Ar message Ar command...
.Nm
did not understand
.Ar command .
A human-readable
.Ar message
is provided.
.El
.\"
.\"==========
.Sh EXAMPLES
.\"==========
Without arguments,
.Dl % playd
will produce a list of available devices:
.Bd -literal -offset indent
0: HDA ATI SB: ALC892 Analog (hw:0,0)
1: HDA ATI SB: ALC892 Digital (hw:0,1)
2: HDA ATI SB: ALC892 Alt Analog (hw:0,2)
3: HDA NVidia: ID 42 Digital (hw:1,3)
4: Plantronics GameCom 780: USB Audio (hw:2,0)
5: sysdefault
6: front
7: surround40
8: default
9: dmix
.Ed
.Pp
Say we want to output on the GameCon.
The command
.Dl % playd 4
will start
.Nm
on its default address (localhost) and port, outputting on device ID 4.
.Pp
To change the address and port, we specify them as arguments:
.Dl % playd 4 127.0.0.1 1350
.Pp
To connect to
.Nm
from the terminal, we can use
.Xr nc 1 :
.Dl % nc 127.0.0.1 1350
.Pp
A session with
.Nm
may look like the following:
.Bd -literal -offset indent
-> OHAI 'playd v0.1.1'
-> FEATURES End FileLoad PlayStop Seek TimeReport
-> TIME 0
-> STATE Ejected
<- load '/usr/home/foo/awesome-mix.mp3'
-> OK load '/usr/home/foo/awesome-mix.mp3'
-> FILE '/usr/home/foo/awesome-mix.mp3'
-> STATE Stopped
<- play
-> OK play
-> STATE Playing
(file plays to end)
-> END
-> STATE Stopped
-> TIME 0
-> eject
<- OK eject
-> STATE Ejected
(disconnect)
.Ed
.\"
.\"=========
.Sh AUTHORS
.\"=========
In alphabetical surname order, the main contributors to
.Nm
at time of writing are:
.Bl -item -offset indent
.It
.An Charles Pigott Aq charles.pigott@ury.org.uk
.It
.An Sam Willcocks Aq sam.w@ury.org.uk
.It
.An Matt Windsor Aq matt.windsor@ury.org.uk
.El
.\"
.\"======
.Sh BUGS
.\"======
Behaviour when escaping multi-byte UTF-8 characters with
.Dq \e
is undefined; this is intentional, for reasons of code simplicity.
